// Package wasm — Module 53 Adversarial Testing: Zero-Copy Buffer Overflow Attacks (Task #264).
//
// This file contains machine-checkable tests demonstrating buffer-overflow attack vectors
// against the zero-copy buffer view system, plus direct verification of the Hoare triple
// {Pre} GuardedAccess {Post} rendered in theoretical_memory_safety.go.
//
// Generated by Task #264, CloudAI Fusion MoAT Research, 2026-08-24.
// Run with: go test ./pkg/wasm -run 'TestAdversarial_Zero|TestHoare' -v

package wasm

import (
	"context"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/cloudai-fusion/cloudai-fusion/pkg/capability"
)

// ============================================================================
// Attack Class 1: Buffer Overflow (CVE-style out-of-bounds descriptor requests)
// ============================================================================

// TestAdversarial_ZeroViewOOBLengthClamped: offset is valid but offset+length would
// spill past the backing buffer. The production defense CLAMPS the length to the
// remaining valid bytes instead of ever exposing memory beyond the buffer.
func TestAdversarial_ZeroViewOOBLengthClamped(t *testing.T) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()

	const size = 1024 * 1024 // 1MB
	handle, err := svc.Alloc(ctx, size)
	if err != nil {
		t.Fatalf("alloc failed: %v", err)
	}
	grant := &Grant{GPU: &GPURule{AllowedDevices: []int{0}}}

	// offset=900KB (valid), length=200KB → 1.1MB > 1MB.
	offset := uint32(900 * 1024)
	length := uint32(200 * 1024)
	desc, err := GetZeroView(ctx, svc, grant, handle, offset, length)
	if err != nil {
		t.Fatalf("expected clamp (no error), got: %v", err)
	}
	if desc == nil {
		t.Fatal("expected clamped descriptor, got nil")
	}
	if uint64(desc.Offset)+uint64(desc.Length) > size {
		t.Fatalf("SAFETY VIOLATION: clamped view [%d,%d) exceeds buffer size %d",
			desc.Offset, desc.Offset+desc.Length, size)
	}
	t.Logf("✅ length clamped from %d to %d; view stays inside buffer", length, desc.Length)
}

// TestAdversarial_ZeroViewOOBOffsetRejected: offset alone exceeds the buffer size, so no
// valid overlap exists. The monitor must fail closed with ErrOutOfBounds.
func TestAdversarial_ZeroViewOOBOffsetRejected(t *testing.T) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()

	const size = 100 * 1024 // 100KB
	handle, err := svc.Alloc(ctx, size)
	if err != nil {
		t.Fatalf("alloc failed: %v", err)
	}
	grant := &Grant{GPU: &GPURule{AllowedDevices: []int{0}}}

	desc, err := GetZeroView(ctx, svc, grant, handle, uint32(200*1024), uint32(10*1024))
	if desc != nil || err == nil {
		t.Fatalf("expected rejection for offset>size, got desc=%v err=%v", desc, err)
	}
	if err != ErrOutOfBounds {
		t.Fatalf("expected ErrOutOfBounds, got %v", err)
	}
	t.Log("✅ offset beyond buffer rejected with ErrOutOfBounds")
}

// TestAdversarial_ForgedHandleRejected proves a guest cannot fabricate a handle to reach a
// buffer it was never granted. Handles are opaque ShardKeys minted by the allocator;
// an unknown value fails the liveness check (BufferLive=false ⇒ Safe(S)=false).
func TestAdversarial_ForgedHandleRejected(t *testing.T) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()
	grant := &Grant{GPU: &GPURule{AllowedDevices: []int{0}}}

	forged := []uint64{
		0xFFFFFFFFFFFFFFFF,       // all-ones
		999_999_999_999,          // large arbitrary
		uint64(EncodeShardKey(3, 7)), // well-formed shard key that was never allocated
	}
	for _, h := range forged {
		desc, err := GetZeroView(ctx, svc, grant, h, 0, 1024)
		if desc != nil || err == nil {
			t.Fatalf("forged handle %d admitted (desc=%v err=%v)", h, desc, err)
		}
	}
	t.Log("✅ all forged handles rejected (unforgeability holds)")
}

// TestAdversarial_ZeroViewNilGrantRejected: a valid live handle must still be denied when
// the caller carries no GPU capability. CapabilityGranted(S)=false ⇒ Safe(S)=false.
func TestAdversarial_ZeroViewNilGrantRejected(t *testing.T) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()

	handle, err := svc.Alloc(ctx, 1024*1024)
	if err != nil {
		t.Fatalf("alloc failed: %v", err)
	}

	cases := []struct {
		name  string
		grant *Grant
	}{
		{"nil-grant", nil},
		{"empty-grant", NewDefaultGrant()},
		{"empty-device-list", &Grant{GPU: &GPURule{AllowedDevices: []int{}}}},
		{"unauthorized-device", &Grant{GPU: &GPURule{AllowedDevices: []int{99}}}},
	}
	for _, tc := range cases {
		desc, err := GetZeroView(ctx, svc, tc.grant, handle, 0, 1024)
		if desc != nil || err == nil {
			t.Errorf("%s: expected denial, got desc=%v err=%v", tc.name, desc, err)
			continue
		}
		t.Logf("✅ %s denied: %v", tc.name, err)
	}
}

// TestAdversarial_UseAfterFree: freeing a handle then re-viewing it must fail. This closes
// a use-after-free path where a guest keeps a stale handle after releasing the buffer.
func TestAdversarial_UseAfterFree(t *testing.T) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()
	grant := &Grant{GPU: &GPURule{AllowedDevices: []int{0}}}

	handle, err := svc.Alloc(ctx, 4096)
	if err != nil {
		t.Fatalf("alloc failed: %v", err)
	}
	// Valid before free.
	if _, err := GetZeroView(ctx, svc, grant, handle, 0, 1024); err != nil {
		t.Fatalf("pre-free view should succeed: %v", err)
	}
	if err := svc.Free(ctx, handle); err != nil {
		t.Fatalf("free failed: %v", err)
	}
	// Must fail after free.
	if desc, err := GetZeroView(ctx, svc, grant, handle, 0, 1024); desc != nil || err == nil {
		t.Fatalf("use-after-free admitted: desc=%v err=%v", desc, err)
	}
	t.Log("✅ use-after-free rejected once handle is released")
}

// TestAdversarial_HandleForkRace stresses the allocator while it is concurrently closed
// (a "fork/teardown" event). Post-close allocations and frees of stale handles must fail
// cleanly with no panic and no data race on the ownership maps.
func TestAdversarial_HandleForkRace(t *testing.T) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	ctx := context.Background()

	var allocOK, freeFail atomic.Int64
	var wg sync.WaitGroup

	wg.Add(1)
	go func() {
		defer wg.Done()
		for i := 0; i < 5000; i++ {
			if h, err := svc.Alloc(ctx, 4096); err == nil && h != 0 {
				allocOK.Add(1)
			}
		}
	}()

	wg.Add(1)
	go func() {
		defer wg.Done()
		time.Sleep(20 * time.Millisecond)
		_ = svc.Close() // fork/teardown event
	}()

	wg.Add(1)
	go func() {
		defer wg.Done()
		for i := 0; i < 5000; i++ {
			if err := svc.Free(ctx, uint64(i+1)); err != nil {
				freeFail.Add(1)
			}
		}
	}()

	wg.Wait()
	t.Logf("alloc-ok=%d free-rejected=%d (no panic = ownership maps stayed consistent)",
		allocOK.Load(), freeFail.Load())
	if freeFail.Load() == 0 {
		t.Error("expected some frees to be rejected (stale/unknown handles or closed allocator)")
	}
}

// ============================================================================
// Hoare Triple Verification: {Pre} GuardedAccess {Post} for the invariant Safe(S)
// ============================================================================

// TestHoareTriple_SafeStateAdmitted: when Safe(S) holds, the monitor admits and the triple
// holds soundly (admitted ⇒ Safe).
func TestHoareTriple_SafeStateAdmitted(t *testing.T) {
	const size = 1024 * 1024
	handle := uint64(0x2A)
	s := SafetyState{
		Grant:       &Grant{GPU: &GPURule{AllowedDevices: []int{0}}},
		LiveBuffers: map[uint64]uint64{handle: size},
		Access:      AddressRegion{Handle: handle, Base: 1024, Length: 1024},
	}
	r := CheckHoareTriple(s)
	if !r.Admitted || !r.PostSafe || !r.TripleHolds {
		t.Fatalf("safe state must be admitted & safe: %+v", r)
	}
	t.Log("✅ Safe(S) ⇒ admitted, triple holds")
}

// TestHoareTriple_UnsafeStatesRejected enumerates the three unsafe categories and verifies
// each is blocked with the correct cause, and that the triple still holds vacuously.
func TestHoareTriple_UnsafeStatesRejected(t *testing.T) {
	const size = 1024 * 1024
	handle := uint64(0x2A)

	cases := []struct {
		name       string
		state      SafetyState
		wantReason string
	}{
		{
			name: "capability-denied",
			state: SafetyState{
				Grant:       &Grant{}, // no GPU rule
				LiveBuffers: map[uint64]uint64{handle: size},
				Access:      AddressRegion{Handle: handle, Base: 0, Length: 1024},
			},
			wantReason: "capability-denied",
		},
		{
			name: "handle-not-live",
			state: SafetyState{
				Grant:       &Grant{GPU: &GPURule{AllowedDevices: []int{0}}},
				LiveBuffers: map[uint64]uint64{}, // empty
				Access:      AddressRegion{Handle: handle, Base: 0, Length: 1024},
			},
			wantReason: "handle-not-live",
		},
		{
			name: "out-of-bounds",
			state: SafetyState{
				Grant:       &Grant{GPU: &GPURule{AllowedDevices: []int{0}}},
				LiveBuffers: map[uint64]uint64{handle: size},
				Access:      AddressRegion{Handle: handle, Base: size, Length: 1024}, // base==size
			},
			wantReason: "out-of-bounds",
		},
		{
			name: "overflow-base-plus-length",
			state: SafetyState{
				Grant:       &Grant{GPU: &GPURule{AllowedDevices: []int{0}}},
				LiveBuffers: map[uint64]uint64{handle: size},
				// Base+Length wraps uint64; InBounds must reject without wrapping.
				Access: AddressRegion{Handle: handle, Base: size - 1, Length: ^uint64(0)},
			},
			wantReason: "out-of-bounds",
		},
	}

	for _, tc := range cases {
		r := CheckHoareTriple(tc.state)
		if r.Admitted {
			t.Errorf("%s: unsafe state was admitted (UNSOUND)", tc.name)
		}
		if !r.TripleHolds {
			t.Errorf("%s: triple must hold vacuously when access is blocked", tc.name)
		}
		if r.RejectReason != tc.wantReason {
			t.Errorf("%s: reject reason = %q, want %q", tc.name, r.RejectReason, tc.wantReason)
		}
	}
	t.Log("✅ every unsafe state rejected with a stated cause; triple holds vacuously")
}

// TestHoareTriple_ExhaustiveSoundness fuzzes a bounded state space and asserts the core
// soundness property: the monitor NEVER admits an access unless Safe(S) holds. This is a
// (bounded) exhaustive check of the invariant, not just spot samples.
func TestHoareTriple_ExhaustiveSoundness(t *testing.T) {
	const bufSize = 16
	handle := uint64(7)

	grants := []*Grant{
		nil,
		{},
		{GPU: &GPURule{AllowedDevices: []int{}}},
		{GPU: &GPURule{AllowedDevices: []int{0}}},
	}
	liveSets := []map[uint64]uint64{
		{},                       // handle not live
		{handle: 0},              // zero-size (treated as not live)
		{handle: bufSize},        // live
		{handle + 1: bufSize},    // different handle live, ours absent
	}

	checked := 0
	for _, g := range grants {
		for _, live := range liveSets {
			for base := uint64(0); base <= bufSize+2; base++ {
				for length := uint64(0); length <= bufSize+2; length++ {
					s := SafetyState{
						Grant:       g,
						LiveBuffers: live,
						Access:      AddressRegion{Handle: handle, Base: base, Length: length},
					}
					r := CheckHoareTriple(s)
					checked++
					if r.Admitted && !s.Safe() {
						t.Fatalf("UNSOUND: admitted unsafe state grant=%v live=%v base=%d len=%d",
							g, live, base, length)
					}
					if !r.TripleHolds {
						t.Fatalf("triple broke at grant=%v live=%v base=%d len=%d", g, live, base, length)
					}
				}
			}
		}
	}
	t.Logf("✅ exhaustive soundness holds over %d enumerated states", checked)
}

// ============================================================================
// Aggregate adversarial throughput benchmark (defensive cost measurement)
// ============================================================================

// BenchmarkAdversarial_MixedVectors measures the cost of the reference monitor under a
// rotating mix of malicious and legitimate requests.
func BenchmarkAdversarial_MixedVectors(b *testing.B) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()
	handle, _ := svc.Alloc(ctx, 1024*1024)
	grant := &Grant{GPU: &GPURule{AllowedDevices: []int{0}}}

	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		switch i % 5 {
		case 0:
			_, _ = GetZeroView(ctx, svc, grant, handle, 2_000_000, 1024) // OOB offset
		case 1:
			_, _ = GetZeroView(ctx, svc, grant, handle, 900*1024, 200*1024) // clamp
		case 2:
			_, _ = GetZeroView(ctx, svc, grant, 999_999_999_999, 0, 1024) // forged
		case 3:
			_, _ = GetZeroView(ctx, svc, grant, handle, 0, 1024) // legitimate
		case 4:
			_, _ = GetZeroView(ctx, svc, nil, handle, 0, 1024) // nil grant
		}
	}
}
