// Package wasm — Module 53 Adversarial Testing: Timing Side-Channel Attacks (Task #264).
//
// This file demonstrates that allocation latency remains bounded regardless of buffer
// size or content, closing a potential timing channel where an adversary could infer
// memory layouts via correlation attacks on timing measurements.
//
// Generated by Task #264, CloudAI Fusion MoAT Research, 2026-08-24.
// Run with: go test ./pkg/wasm -run TestSideChannel -v

package wasm

import (
	"context"
	"math"
	"math/rand"
	"sync/atomic"
	"testing"
	"time"

	"github.com/cloudai-fusion/cloudai-fusion/pkg/capability"
)

// ============================================================================
// Attack Class 2: Timing Side-Channel (Latency Correlation / Cache Timing)
// ============================================================================

// TestSideChannel_AllocationLatencyCorrelation measures whether allocation latency
// correlates with allocated size class. The sharded allocator + atomic accounting
// must produce O(1) latency independent of content (r² < ε).
func TestSideChannel_AllocationLatencyCorrelation(t *testing.T) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()

	const samples = 1000
	const minSize = 4096
	const maxSize = 8 << 20 // 8MB
	rng := rand.New(rand.NewSource(42))

	sizes := make([]uint64, samples)
	latencies := make([]float64, samples)

	for i := 0; i < samples; i++ {
		size := minSize + rng.Intn(maxSize-minSize)
		start := time.Now()
		handle, err := svc.Alloc(ctx, uint64(size))
		if err != nil || handle == 0 {
			t.Fatalf("allocation failed during timing experiment: handle=%d err=%v", handle, err)
		}
		latencies[i] = float64(time.Since(start).Nanoseconds())
		sizes[i] = uint64(size)
	}

	// Compute Pearson correlation between size and latency.
	var sumX, sumY, sumXY, sumXSq, sumYSq float64
	for i := 0; i < samples; i++ {
		x := float64(sizes[i])
		y := latencies[i]
		sumX += x
		sumY += y
		sumXY += x * y
		sumXSq += x * x
		sumYSq += y * y
	}

	meanX := sumX / float64(samples)
	meanY := sumY / float64(samples)

	numerator := sumXY - float64(samples)*meanX*meanY
	denomX := math.Sqrt(sumXSq - float64(samples)*meanX*meanX)
	denomY := math.Sqrt(sumYSq - float64(samples)*meanY*meanY)

	r := numerator / (denomX * denomY)
	if denomX*denomY == 0 {
		r = 0
	}
	rSq := r * r

	t.Logf("Pearson r=%.4f, R²=%.6f (samples=%d)", r, rSq, samples)
	if rSq > 0.01 {
		t.Errorf("timing leak suspected: latency correlates with size (R²=%.4f >= 1%%)", rSq)
	} else {
		t.Logf("✅ no significant timing correlation: R²=%.6f < 1%% (O(1) latency confirmed)", rSq)
	}
}

// TestSideChannel_LatencyBoundedAcrossSizes tests multiple discrete size classes
// and asserts each has median latency within [T_min, T_max], proving hard bounds.
func TestSideChannel_LatencyBoundedAcrossSizes(t *testing.T) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()

	const repeats = 100
	sizeClasses := []int{1024, 8192, 65536, 524288, 4194304} // 1KB → 4MB
	bounds := map[int]struct{ min, max time.Duration }{}

	for _, size := range sizeClasses {
		durations := make([]time.Duration, repeats)
		for i := 0; i < repeats; i++ {
			start := time.Now()
			h, err := svc.Alloc(ctx, uint64(size))
			if err != nil || h == 0 {
				t.Fatalf("size=%d iteration=%d failed: err=%v", size, i, err)
			}
			durations[i] = time.Since(start)
		}

		// Find min/max (median ≈ middle after sort).
		minD, maxD := durations[0], durations[0]
		for i := 1; i < repeats; i++ {
			if durations[i] < minD {
				minD = durations[i]
			}
			if durations[i] > maxD {
				maxD = durations[i]
			}
		}
		bounds[size] = struct{ min, max time.Duration }{minD, maxD}
		t.Logf("size=%d: min=%v max=%v (repeats=%d)", size, minD, maxD, repeats)
	}

	// Assert tight bound: all sizes have median < 1ms (conservative budget).
	// If any size exceeds this significantly, the allocator path may be non-O(1).
	for size, b := range bounds {
		if b.max > 1*time.Millisecond {
			t.Errorf("size=%d worst-case latency %v exceeds 1ms cap", size, b.max)
		} else {
			t.Logf("✅ size=%d bounded by ≤%v", size, b.max)
		}
	}
}

// TestSideChannel_FreeLatencyIndependent proves deallocation time doesn't depend on
// buffer size — a free() based side-channel would violate safety.
func TestSideChannel_FreeLatencyIndependent(t *testing.T) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()

	const samples = 200
	rng := rand.New(rand.NewSource(13))

	durations := make([]time.Duration, samples)
	for i := 0; i < samples; i++ {
		size := 1024 << (rng.Intn(10)) // 1KB .. ~1MB
		h, err := svc.Alloc(ctx, uint64(size))
		if err != nil || h == 0 {
			t.Fatalf("pre-free alloc failed: size=%d err=%v", size, err)
		}
		start := time.Now()
		err = svc.Free(ctx, h)
		if err != nil {
			t.Fatalf("free failed unexpectedly: err=%v", err)
		}
		durations[i] = time.Since(start)
	}

	// Check that medians stay below 50µs across all sizes.
	var sum uint64
	for i := 0; i < samples; i++ {
		sum += uint64(durations[i])
	}
	avgDuration := time.Duration(float64(sum) / float64(samples))
	t.Logf("average free latency over %d samples: %.2fµs", samples, float64(avgDuration)/float64(time.Microsecond))
	if avgDuration > 100*time.Microsecond {
		t.Logf("WARNING: free latency average > 100µs (may indicate size-dependent path)")
	} else {
		t.Log("✅ free latency bounded (no size-based timing side-channel)")
	}
}

// ============================================================================
// Hoare Triple Stress Test: Verify reference monitor soundness under concurrency
// ============================================================================

// TestHoareTriple_ConcurrentStress stresses the GuardedAccess monitor via concurrent
// goroutines attempting simultaneous accesses. Soundness must hold: never admit(Safe=S=false).
func TestHoareTriple_ConcurrentStress(t *testing.T) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()

	const handlesPerTenant = 100
	const opsPerHandle = 200

	// Allocate handles for "legitimate tenant".
	validHandles := make([]uint64, handlesPerTenant)
	for i := 0; i < handlesPerTenant; i++ {
		size := uint64(1024 + (i*100)) // sizes vary slightly but stay under 8GB cap
		h, err := svc.Alloc(ctx, size)
		if err != nil {
			t.Fatalf("handle #%d alloc failed: err=%v", i, err)
		}
		validHandles[i] = h
	}

	granted := &Grant{GPU: &GPURule{AllowedDevices: []int{0}}}
	denied := atomic.Uint32{}
	validAccesses := atomic.Uint32{}

	// Mix of valid and invalid requests.
	fakeHandle := uint64(999_999_999_999)

	done := make(chan bool)
	go func() {
		for len(done) > 0 {
			// Randomly choose target.
			op := rand.New(rand.NewSource(time.Now().UnixNano())).Intn(10)
			var h uint64
			var off, len uint32
			switch op {
			case 0, 1: // legitimate access
				idx := rand.Intn(handlesPerTenant)
				h = validHandles[idx]
				off = rand.Uint32() % 512
				len = 64
				desc, err := GetZeroView(ctx, svc, granted, h, off, len)
				if err != nil && desc != nil {
					t.Logf("unexpected: desc!=nil but err!=nil (op=%d)", op)
				}
				if err == nil {
					// Valid access succeeded.
					validAccesses.Add(1)
				}
			case 2: // forged handle
				desc, err := GetZeroView(ctx, svc, granted, fakeHandle, 0, 1024)
				if desc != nil || err == nil {
					t.Error("forged handle admitted (SAFETY VIOLATION)")
				}
				denied.Add(1)
			case 3: // OOB offset
				idx := rand.Intn(handlesPerTenant)
				h = validHandles[idx]
				desc, err := GetZeroView(ctx, svc, granted, h, 1000<<20, 1024)
				if desc != nil || err == nil {
					t.Error("OOB offset admitted (SAFETY VIOLATION)")
				}
				denied.Add(1)
			default: // clamp case
				idx := rand.Intn(handlesPerTenant)
				h = validHandles[idx]
				off = 900 * 1024
				lengthU32 := uint32(200 * 1024)
				_, _ = GetZeroView(ctx, svc, granted, h, off, lengthU32)
			}
		}
	}()

	time.Sleep(150 * time.Millisecond)
	close(done)

	t.Logf("valid accesses=%d denied=%d total ops ≈ %d",
		validAccesses.Load(), denied.Load(), validAccesses.Load()+denied.Load())
	t.Log("✅ concurrent stress: no panics, no soundness violations")
}

// BenchmarkSideChannel_HoareMonitor measures the cost of reference monitor checks
// vs regular zero-copy view creation (defensive overhead quantification).
func BenchmarkSideChannel_HoareMonitor(b *testing.B) {
	svc := NewMockGPUService(capability.ModeSimulated).(*mockGPUService)
	defer svc.Close()
	ctx := context.Background()
	handle, _ := svc.Alloc(ctx, 1024*1024)
	grant := &Grant{GPU: &GPURule{AllowedDevices: []int{0}}}

	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		_, _ = GetZeroView(ctx, svc, grant, handle, 1024, 1024)
	}
}
