#!/usr/bin/env python3
"""
Task 91: Real sklearn baseline computation for joint anomaly detection.

This script runs sklearn's IsolationForest (IF) and LocalOutlierFactor (LOF) on
the exact datasets generated by TestExportSklearnBenchmarkData. For each dataset,
it:

1. Loads features, labels (0/1), and is_test flag (0/1).
2. Fits IF and LOF **only** on rows where is_test == 1, ensuring identical evaluation 
   conditions to the Go detectors (warmup excluded from fit).
3. Scores all points where is_test == 1 and computes Precision, Recall, F1, AUC-ROC.
4. Measures total wall-clock time (fit + scoring) and reports mean latency_per_point_ms.
5. Writes sklearn_metrics.csv with one row per (scenario, seed, detector).

Usage:
    $env: PYTHONIOENCODING="utf-8"
    python pkg/anomaly/sklearn_runner.py <out_dir>

where out_dir is the directory containing go_metrics.csv and all *.csv dataset files.
Outputs are written to the same out_dir as sklearn_metrics.csv.

Environment variable: ANOMALY_EXPORT can be set to "1" to match the Go test, but
this script doesn't skip; it always runs the actual model training and scoring.
"""

import csv
import json
import os
import sys
import time
from pathlib import Path

import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

def load_dataset(path: Path):
    """Load feature matrix, labels, and is_test flags."""
    data = np.loadtxt(path, delimiter=",", ndmin=2)
    n, _ = data.shape
    # Last two columns: label, is_test
    labels = data[:, -2].astype(int)
    is_test = data[:, -1].astype(int)
    X = data[:, :-2]
    return X, labels, is_test


def compute_metrics(y_true: np.ndarray, scores: np.ndarray, threshold: float | None = None):
    """Compute Precision, Recall, F1, AUC-ROC given true labels and anomaly scores."""
    if len(np.unique(y_true)) < 2:
        raise ValueError("Labels must contain both positive and negative classes.")
    
    auc = roc_auc_score(y_true, scores)
    
    # Default threshold is median; we'll also report F1 using a contamination-like cutoff.
    if threshold is not None:
        preds = (scores > threshold).astype(int)
    else:
        preds = (scores > np.median(scores)).astype(int)
    
    if preds.sum() == 0:
        # Avoid divide-by-zero in precision/F1
        prec = 0.0
        rec = 0.0
        f1 = 0.0
    else:
        prec = precision_score(y_true, preds)
        rec = recall_score(y_true, preds)
        f1 = f1_score(y_true, preds)
    
    return prec, rec, f1, auc


def run_sklearn_baselines(X: np.ndarray, labels: np.ndarray, is_test: np.ndarray, seed: int):
    """Fit IF on test-region rows only; score them; return metrics + latencies."""
    mask = is_test == 1
    X_test = X[mask]
    y_test = labels[mask]
    n_points = len(y_test)
    print(f"  IsolationForest({n_points} points): fit={t0:.2f}s -> {prec:.4f}, {rec:.4f}, {f1:.4f}, AUC={auc:.4f}")
    
    t0_if = time.perf_counter()
    clf_if = IsolationForest(
        contamination=0.15,  # match test region's ~15% anomaly fraction
        n_estimators=150,
        max_samples="auto",
        random_state=seed,
        n_jobs=-1,
    )
    clf_if.fit(X_test)
    if_scores = clf_if.decision_function(X_test)
    t1_if = time.perf_counter()
    
    prec_if, rec_if, f1_if, auc_if = compute_metrics(y_test, if_scores, threshold=np.median(if_scores))
    if_fit_time_ms = (t1_if - t0_if) * 1000.0
    if_latency = if_fit_time_ms / n_points
    return (prec_if, rec_if, f1_if, auc_if, if_latency), (if_fit_time_ms, if_latency)


def main():
    if len(sys.argv) < 2:
        print("Usage: python sklearn_runner.py <out_dir>")
        sys.exit(1)

    out_dir = Path(sys.argv[1])
    if not out_dir.exists():
        print(f"Error: {out_dir} does not exist")
        sys.exit(1)

    print(f"Python {sys.version.split()[0]}, sklearn {__import__('sklearn').__version__}")
    print(f"Reading datasets from {out_dir}")

    metric_rows = []
    dataset_files = sorted([f for f in out_dir.glob("*.csv") if f.name != "go_metrics.csv"])

    for csv_file in dataset_files:
        print(f"\nProcessing {csv_file.stem}:")
        try:
            X, labels, is_test = load_dataset(csv_file)
            seed = int(out_dir.name.split("_")[2]) if "_seed" in csv_file.stem else 0
            scenario = csv_file.stem.split("_")[0] if "_" in csv_file.stem else "unknown"
            
            # Run sklearn baselines
            (prec_if, rec_if, f1_if, auc_if, if_lat), (if_fit, if_tot) = run_sklearn_baselines(X, labels, is_test, seed)
            (lof_prec, lof_rec, lof_f1, lof_auc, lof_lat) = run_lof(X, labels, is_test, seed)
            
            # Write sklearn metrics
            metric_rows.append({
                "scenario": scenario,
                "d": X.shape[1],
                "rho": 0.75,  # fixed config
                "seed": seed,
                "detector": "isolation_forest",
                "precision": prec_if,
                "recall": rec_if,
                "f1": f1_if,
                "auc": auc_if,
                "latency_per_point_ms": if_lat,
            })
            metric_rows.append({
                "scenario": scenario,
                "d": X.shape[1],
                "rho": 0.75,
                "seed": seed,
                "detector": "local_outlier_factor",
                "precision": lof_prec,
                "recall": lof_rec,
                "f1": lof_f1,
                "auc": lof_auc,
                "latency_per_point_ms": lof_lat,
            })
        except Exception as e:
            print(f"Error processing {csv_file}: {e}")
            continue

    # Write sklearn_metrics.csv
    metrics_path = out_dir / "sklearn_metrics.csv"
    if metric_rows:
        with open(metrics_path, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=[
                "scenario", "d", "rho", "seed", "detector", 
                "precision", "recall", "f1", "auc", "latency_per_point_ms"
            ])
            writer.writeheader()
            writer.writerows(metric_rows)
        print(f"\nWrote {len(metric_rows)} rows to {metrics_path}")
    else:
        print("\nNo metrics written (no valid datasets found)")
        sys.exit(1)


def run_lof(X, labels, is_test, seed):
    """Fit LOF on test-region rows; score them; return metrics + latencies."""
    mask = is_test == 1
    X_test = X[mask]
    y_test = labels[mask]
    n_points = len(y_test)
    
    # Use novelty=False (classic LOF) — fit_predict returns labels (-1/+1).
    # But we need scores: use negative_outlier_factor_ and invert.
    t0_lof = time.perf_counter()
    lof = LocalOutlierFactor(
        n_neighbors=min(20, max(2, n_points // 5)),  # adaptive k
        contamination=0.15,  # match test region's ~15% anomaly rate
        novelty=False,
        n_jobs=-1,
    )
    lof_pred = lof.fit_predict(X_test)
    lof_scores = -lof.negative_outlier_factor_  # higher => more anomalous
    t1_lof = time.perf_counter()
    fit_time_ms = (t1_lof - t0_lof) * 1000.0
    
    # Threshold: we compare predictions vs ground truth
    # If contamination matches true rate, the count of predicted anomalies should ≈ count of true positives
    prec, rec, f1, auc = compute_metrics(y_test, lof_scores, threshold=None)
    
    # Latency estimate: fit dominates; inference cost is negligible
    # Approximation: treat all time as fit-time, spread over n points
    lof_latency = fit_time_ms / n_points  # ms per point (conservative upper bound)
    
    return (prec, rec, f1, auc), (fit_time_ms, lof_latency)


if __name__ == "__main__":
    main()
