// Package detection_rules provides SIEM (Security Information and Event Management) 
// detection rules for automated security monitoring and incident response.
// This module implements industry-standard detection patterns aligned with MITRE ATT&K.
package detection_rules

import (
	"fmt"
	"regexp"
	"strings"
	"time"
)

// RuleCategory categorizes detection rules by attack type
type RuleCategory string

const (
	CategoryBufferOverflow   RuleCategory = "BUFFER_OVERFLOW"
	CategoryInjection        RuleCategory = "INJECTION"
	CategoryExploitation     RuleCategory = "EXPLOITATION"
	CategoryPrivilegeEscape  RuleCategory = "PRIVILEGE_ESCALATION"
	CategoryPersistence      RuleCategory = "PERSISTENCE"
	CategoryDefenseEvasion   RuleCategory = "DEFENSE_EVASION"
	CategoryCredentialAccess RuleCategory = "CREDENTIAL_ACCESS"
	CategoryDiscovery        RuleCategory = "DISCOVERY"
	CategoryLateralMovement  RuleCategory = "LATERAL_MOVEMENT"
	CategoryCollection       RuleCategory = "COLLECTION"
	CategoryCommandControl   RuleCategory = "COMMAND_CONTROL"
	CategoryExfiltration     RuleCategory = "EXFILTRATION"
	CategoryImpact           RuleCategory = "IMPACT"
	CategoryUnknown          RuleCategory = "UNKNOWN"
)

// Severity level for alerts
type Severity string

const (
	Critical Severity = "CRITICAL"
	High     Severity = "HIGH"
	Medium   Severity = "MEDIUM"
	Low      Severity = "LOW"
	Info     Severity = "INFO"
)

// DetectionStatus tracks rule evaluation state
type DetectionStatus string

const (
	StatusActive     DetectionStatus = "ACTIVE"
	StatusDisabled   DetectionStatus = "DISABLED"
	StatusPreview    DetectionStatus = "PREVIEW"
	StatusDeprecated DetectionStatus = "DEPRECATED"
)

// DetectionRule represents a single SIEM detection rule
type DetectionRule struct {
	ID              string            `json:"rule_id"`
	Name            string            `json:"name"`
	Description     string            `json:"description"`
	DetectionLogic  string            `json:"detection_logic"`
	SyntaxType      string            `json:"syntax_type"` // syslog, json, cef, siem_custom
	Severity        Severity          `json:"severity"`
	RuleCategory    RuleCategory      `json:"category"`
	MITREATTK       string            `json:"mitre_attack,omitempty"`
	MITRETechnique  string            `json:"mitre_technique,omitempty"`
	Tactic          string            `json:"tactic,omitempty"`
	Impact          string            `json:"impact,omitempty"`
	ThreatTypes     []string          `json:"threat_types,omitempty"`
	DataSources     []string          `json:"data_sources,omitempty"`
	RequiredFields  []string          `json:"required_fields,omitempty"`
	ExampleLogs     []string          `json:"example_logs,omitempty"`
	ReferenceLinks  []string          `json:"reference_links,omitempty"`
	CreatedDate     string            `json:"created_date"`
	LastModified    string            `json:"last_modified"`
	Version         string            `json:"version"`
	Author          string            `json:"author,omitempty"`
	Status          DetectionStatus   `json:"status"`
	IsAutoGenerated bool              `json:"is_auto_generated,omitempty"`
	ComplianceTags  map[string]string `json:"compliance_tags,omitempty"`
}

// AlertEvent represents a security event that triggered a rule
type AlertEvent struct {
	RuleID         string                 `json:"rule_id"`
	RuleName       string                 `json:"rule_name"`
	Timestamp      time.Time              `json:"timestamp"`
	Severity       Severity               `json:"severity"`
	AlertCategory  RuleCategory           `json:"category"`
	Description    string                 `json:"description"`
	EventData      map[string]interface{} `json:"event_data,omitempty"`
	SourceIP       string                 `json:"source_ip,omitempty"`
	DestinationIP  string                 `json:"destination_ip,omitempty"`
	User           string                 `json:"user,omitempty"`
	Evidence       string                 `json:"evidence"`
	MITREATTK      string                 `json:"mitre_attack,omitempty"`
	Mitigation     string                 `json:"mitigation,omitempty"`
	ResponseAction string                 `json:"response_action,omitempty"`
}

// DetectionEngine evaluates events against registered rules
type DetectionEngine struct {
	rules          map[string]DetectionRule
	dynamicRules   map[string]func(event map[string]interface{}) bool
	alertHistory   []*AlertEvent
	enabledRules   map[string]bool
	config         *EngineConfig
}

// EngineConfig configures detection engine behavior
type EngineConfig struct {
	DefaultSeverity     Severity
	MaxAlertsPerEvent   int
	EnableMITREMapping  bool
	ComplianceProfiles  []string // PCI-DSS, HIPAA, NIST, SOC2
	AlertThrottling     bool
	ThrottleWindow      time.Duration
	NotificationChannels []string // email, slack, pagerduty, siem
}

// DefaultEngineConfig returns safe defaults for production use
func DefaultEngineConfig() *EngineConfig {
	return &EngineConfig{
		DefaultSeverity:      Medium,
		MaxAlertsPerEvent:    100,
		EnableMITREMapping:   true,
		ComplianceProfiles:   []string{"PCI-DSS", "NIST"},
		AlertThrottling:      true,
		ThrottleWindow:       5 * time.Minute,
		NotificationChannels: []string{},
	}
}

// NewDetectionEngine creates new detection engine with specified configuration
func NewDetectionEngine(config *EngineConfig) *DetectionEngine {
	if config == nil {
		config = DefaultEngineConfig()
	}
	
	engine := &DetectionEngine{
		rules:          make(map[string]DetectionRule),
		dynamicRules:   make(map[string]func(event map[string]interface{}) bool),
		alertHistory:   make([]*AlertEvent, 0),
		enabledRules:   make(map[string]bool),
		config:         config,
	}
	
	// Load built-in rules
	engine.LoadBuiltInRules()
	
	return engine
}

// DefaultNewDetectionEngine returns legacy-compatible instance
func DefaultNewDetectionEngine() *DetectionEngine {
	return NewDetectionEngine(nil)
}

// LoadBuiltInRules loads all predefined detection rules
func (de *DetectionEngine) LoadBuiltInRules() {
	// Buffer Overflow Attack Detection Rules
	de.addRule(BufferOverflowPattern1())
	de.addRule(BufferOverflowPattern2())
	de.addRule(BufferOverflowPattern3())
	
	// Format String Vulnerability Rules
	de.addRule(FormatStringAttackRule())
	
	// Code Injection Rules
	de.addRule(SQLInjectionRule())
	de.addRule(CommandInjectionRule())
	de.addRule(CodeInjectionRule())
	
	// Exploitation Detection Rules
	de.addRule(ExploitAttemptRule())
	de.addRule(MemoryCorruptionRule())
	
	// Privilege Escalation Rules
	de.addRule(PrivilegeEscalationRule())
	de.addRule(LocalPrivilegeEscalation())
	
	// Defense Evasion Rules
	de.addRule(TAMPERingDetectionRule())
	de.addRule(AuditBypassRule())
	
	// Credential Access Rules
	de.addRule(CredentialDumpingRule())
	de.addRule(PassTheHashRule())
	
	// Persistence Rules
	de.addRule(SuspiciousProcessRule())
	de.addRule(SystemModificationRule())
	
	// Network Activity Rules
	de.addRule(C2CommunicationRule())
	de.addRule(LateralMovementRule())
	
	// Data Exfiltration Rules
	de.addRule(DataExfilRule())
	de.addRule(LargeOutboundTransfer())
	
	fmt.Printf("✓ Loaded %d built-in detection rules\n", len(de.rules))
}

// addRule registers a single rule in the engine
func (de *DetectionEngine) addRule(rule DetectionRule) {
	de.rules[rule.ID] = rule
	de.enabledRules[rule.ID] = true
}

// createAlert generates alert from matched rule
func (de *DetectionEngine) createAlert(rule DetectionRule, event map[string]interface{}) *AlertEvent {
	alert := &AlertEvent{
		RuleID:        rule.ID,
		RuleName:      rule.Name,
		Timestamp:     time.Now(),
		Severity:      rule.Severity,
		AlertCategory: rule.RuleCategory,
		Description:   rule.Description,
		EventData:     event,
		Evidence:      fmt.Sprintf("%v", event),
		MITREATTK:     rule.MITREATTK,
	}
	
	// Extract common fields from event
	if srcIP, ok := event["source_ip"].(string); ok {
		alert.SourceIP = srcIP
	}
	if dstIP, ok := event["destination_ip"].(string); ok {
		alert.DestinationIP = dstIP
	}
	if user, ok := event["user"].(string); ok {
		alert.User = user
	}
	
	// Add mitigation guidance
	alert.Mitigation = de.getMitigationGuide(rule)
	
	// Add response action
	alert.ResponseAction = de.getResponseAction(rule.Severity)
	
	de.alertHistory = append(de.alertHistory, alert)
	
	return alert
}

// getMitigationGuide provides remediation guidance for detected threat
func (de *DetectionEngine) getMitigationGuide(rule DetectionRule) string {
	mitigationMap := map[RuleCategory]string{
		CategoryBufferOverflow:   "Patch vulnerable functions, enable stack canaries (-fstack-protector), use ASLR and DEP",
		CategoryInjection:        "Implement input validation, use parameterized queries, sanitize all user inputs",
		CategoryExploitation:     "Apply security patches, deploy WAF/IPS, restrict execution permissions",
		CategoryPrivilegeEscape:  "Implement principle of least privilege, patch OS vulnerabilities, monitor privileged operations",
		CategoryPersistence:      "Review startup locations, scan scheduled tasks, audit service installations",
		CategoryDefenseEvasion:   "Enable comprehensive logging, maintain integrity monitoring, enforce application control",
		CategoryCredentialAccess: "Implement MFA, disable NTLM, use credential guard, monitor LSASS access",
		CategoryDiscovery:        "Restrict network enumeration, limit system information exposure, log discovery tools",
		CategoryLateralMovement:  "Network segmentation, disable admin shares, monitor RDP/SMB usage",
		CategoryCollection:       "Limit data access, implement DLP, monitor clipboard and screenshot activity",
		CategoryCommandControl:   "Block known C2 infrastructure, inspect outbound traffic, deploy DNS filtering",
		CategoryExfiltration:     "Enforce encryption, monitor large transfers, implement egress filtering",
		CategoryImpact:           "Maintain backups, test recovery procedures, isolate affected systems",
		CategoryUnknown:          "Investigate root cause, collect forensic evidence, escalate to security team",
	}
	
	if guide, ok := mitigationMap[rule.RuleCategory]; ok {
		return guide
	}
	return "Conduct thorough investigation and follow incident response procedures"
}

// getResponseAction determines appropriate response based on severity
func (de *DetectionEngine) getResponseAction(severity Severity) string {
	responseMap := map[Severity]string{
		Critical: "Immediate containment required - activate incident response team within 1 hour",
		High:     "Urgent response needed - investigate and mitigate within 4 hours",
		Medium:   "Standard response - address within 24 hours during business hours",
		Low:      "Monitoring recommended - review during routine security assessment",
		Info:     "Awareness only - document for baseline and future comparison",
	}
	
	if response, ok := responseMap[severity]; ok {
		return response
	}
	return "Assess and respond according to organizational policy"
}

// Evaluate checks event against all enabled rules and returns matching alerts
func (de *DetectionEngine) Evaluate(event map[string]interface{}) []*AlertEvent {
	var alerts []*AlertEvent
	
	for id, rule := range de.rules {
		if !de.enabledRules[id] {
			continue
		}
		
		if de.matchesRule(rule, event) {
			alert := de.createAlert(rule, event)
			alerts = append(alerts, alert)
			
			if len(alerts) >= de.config.MaxAlertsPerEvent {
				break
			}
		}
	}
	
	return alerts
}

// matchesRule performs pattern matching against rule logic
func (de *DetectionEngine) matchesRule(rule DetectionRule, event map[string]interface{}) bool {
	logic := strings.ToLower(rule.DetectionLogic)
	
	// Extract relevant fields from event
	var eventStr string
	for key, value := range event {
		eventStr += fmt.Sprintf("%s=%v ", key, value)
	}
	
	// Simple keyword matching for syslog-style detection
	if strings.Contains(logic, "contains") || strings.Contains(logic, "match") {
		pattern := extractRegexFromDetection(logic)
		if pattern != "" {
			re, err := regexp.Compile(pattern)
			if err == nil && re.MatchString(eventStr) {
				return true
			}
		}
	}
	
	// Check specific conditions
	if strings.Contains(logic, "syslog contains \"stack smashing detected\"") &&
		strings.Contains(eventStr, "stack smashing detected") {
		return true
	}
	
	if strings.Contains(logic, "segfault") &&
		strings.Contains(eventStr, "segfault") {
		return true
	}
	
	if strings.Contains(logic, "overflow") &&
		strings.Contains(eventStr, "overflow") {
		return true
	}
	
	return false
}

// extractRegexFromDetection pulls regex pattern from detection logic
func extractRegexFromDetection(detectionLogic string) string {
	re := regexp.MustCompile(`"(.*?)"`)
	matches := re.FindAllStringSubmatch(detectionLogic, -1)
	if len(matches) > 0 {
		return matches[0][1]
	}
	return ""
}

// GetRule returns specific rule by ID
func (de *DetectionEngine) GetRule(ruleID string) (DetectionRule, bool) {
	rule, exists := de.rules[ruleID]
	return rule, exists
}

// GetAllRules returns all registered rules
func (de *DetectionEngine) GetAllRules() []DetectionRule {
	rules := make([]DetectionRule, 0, len(de.rules))
	for _, rule := range de.rules {
		rules = append(rules, rule)
	}
	return rules
}

// EnableRule activates a specific detection rule
func (de *DetectionEngine) EnableRule(ruleID string) error {
	rule, exists := de.rules[ruleID]
	if !exists {
		return fmt.Errorf("rule not found: %s", ruleID)
	}
	
	de.enabledRules[ruleID] = true
	rule.Status = StatusActive
	de.rules[ruleID] = rule
	return nil
}

// DisableRule deactivates a specific detection rule
func (de *DetectionEngine) DisableRule(ruleID string) error {
	rule, exists := de.rules[ruleID]
	if !exists {
		return fmt.Errorf("rule not found: %s", ruleID)
	}
	
	de.enabledRules[ruleID] = false
	rule.Status = StatusDisabled
	de.rules[ruleID] = rule
	return nil
}

// AddDynamicRule registers custom dynamic detection logic
func (de *DetectionEngine) AddDynamicRule(id string, predicate func(event map[string]interface{}) bool) error {
	if _, exists := de.rules[id]; exists {
		return fmt.Errorf("rule already exists: %s", id)
	}
	
	de.dynamicRules[id] = predicate
	
	rule := DetectionRule{
		ID:       id,
		Name:     fmt.Sprintf("Dynamic Rule: %s", id),
		Status:   StatusActive,
		IsAutoGenerated: true,
	}
	de.rules[id] = rule
	de.enabledRules[id] = true
	
	return nil
}

// GetAlertHistory returns historical alerts
func (de *DetectionEngine) GetAlertHistory() []*AlertEvent {
	return copyAlertEvents(de.alertHistory)
}

// ClearHistory clears alert history
func (de *DetectionEngine) ClearHistory() {
	de.alertHistory = de.alertHistory[:0]
}

// ComplianceReport generates compliance mapping report
func (de *DetectionEngine) ComplianceReport() map[string][]string {
	report := make(map[string][]string)
	
	for _, profileStr := range de.config.ComplianceProfiles {
		report[profileStr] = make([]string, 0)
	}
	
	for id, rule := range de.rules {
		if rule.ComplianceTags != nil {
			for profileKey := range rule.ComplianceTags {
				report[profileKey] = append(report[profileKey], id)
			}
		} else {
			report["PCI-DSS"] = append(report["PCI-DSS"], id)
			report["NIST"] = append(report["NIST"], id)
		}
	}
	
	return report
}

// ========== Built-in Detection Rule Definitions ==========

// BufferOverflowPattern1 detects classic buffer overflow attacks
func BufferOverflowPattern1() DetectionRule {
	return DetectionRule{
		ID:             "BO-001",
		Name:           "Stack Smashing Detected",
		Description:    "Detects stack smashing detected errors indicating buffer overflow attempts",
		DetectionLogic: `syslog contains "stack smashing detected"`,
		SyntaxType:     "syslog",
		Severity:       Critical,
		RuleCategory:   CategoryBufferOverflow,
		MITREATTK:      "T1190",
		ThreatTypes:    []string{"Buffer Overflow", "Code Execution"},
		DataSources:    []string{"system logs", "kernel messages", "application crash dumps"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// BufferOverflowPattern2 detects exploitation attempts via shellcode
func BufferOverflowPattern2() DetectionRule {
	return DetectionRule{
		ID:             "BO-002",
		Name:           "Shellcode Execution Attempt",
		Description:    "Identifies potential shellcode injection through memory corruption",
		DetectionLogic: `"execve() syscall detected in non-standard memory region`,
		SyntaxType:     "auditd",
		Severity:       Critical,
		RuleCategory:   CategoryExploitation,
		MITREATTK:      "T1190",
		ThreatTypes:    []string{"Exploitation", "Code Execution", "Memory Corruption"},
		DataSources:    []string{"audit logs", "syscall tracing", "memory dumps"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// BufferOverflowPattern3 detects format string vulnerabilities
func BufferOverflowPattern3() DetectionRule {
	return DetectionRule{
		ID:             "BO-003",
		Name:           "Heap Overflow Pattern",
		Description:    "Identifies heap-based buffer overflow signatures",
		DetectionLogic: `malloc() followed by out-of-bounds write detected`,
		SyntaxType:     "heap_trace",
		Severity:       High,
		RuleCategory:   CategoryBufferOverflow,
		MITREATTK:      "T1190",
		ThreatTypes:    []string{"Heap Overflow", "Memory Safety Violation"},
		DataSources:    []string{"memory profilers", "ASan reports", "valgrind output"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// FormatStringAttackRule detects format string exploits
func FormatStringAttackRule() DetectionRule {
	return DetectionRule{
		ID:             "FS-001",
		Name:           "Format String Attack",
		Description:    "Detects potential format string vulnerabilities being exploited",
		DetectionLogic: `printf(user_input) or snprintf without format specifier`,
		SyntaxType:     "code_analysis",
		Severity:       High,
		RuleCategory:   CategoryInjection,
		MITREATTK:      "T1190",
		ThreatTypes:    []string{"Format String", "Information Disclosure"},
		DataSources:    []string{"static analysis", "dynamic instrumentation", "core dumps"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// SQLInjectionRule detects SQL injection attacks
func SQLInjectionRule() DetectionRule {
	return DetectionRule{
		ID:             "SQLI-001",
		Name:           "SQL Injection Attempt",
		Description:    "Identifies SQL injection patterns in database queries",
		DetectionLogic: `query contains unescaped quotes followed by SQL keywords SELECT UNION DROP`,
		SyntaxType:     "sql_monitor",
		Severity:       Critical,
		RuleCategory:   CategoryInjection,
		MITREATTK:      "T1190",
		ThreatTypes:    []string{"SQL Injection", "Data Breach"},
		DataSources:    []string{"database logs", "WAF logs", "application queries"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// CommandInjectionRule detects command injection attacks
func CommandInjectionRule() DetectionRule {
	return DetectionRule{
		ID:             "CLI-001",
		Name:           "Command Injection Attempt",
		Description:    "Detects command injection vulnerabilities in shell command execution",
		DetectionLogic: `os.system(input) or subprocess with shell=True`,
		SyntaxType:     "code_analysis",
		Severity:       Critical,
		RuleCategory:   CategoryInjection,
		MITREATTK:      "T1190",
		ThreatTypes:    []string{"Command Injection", "Remote Code Execution"},
		DataSources:    []string{"web server logs", "application logs", "intrusion detection"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// CodeInjectionRule detects code injection attacks
func CodeInjectionRule() DetectionRule {
	return DetectionRule{
		ID:             "CODI-001",
		Name:           "Code Injection Attempt",
		Description:    "Identifies eval/exec code injection vulnerabilities",
		DetectionLogic: `eval(input) or exec(input) without sanitization`,
		SyntaxType:     "static_analysis",
		Severity:       Critical,
		RuleCategory:   CategoryInjection,
		MITREATTK:      "T1190",
		ThreatTypes:    []string{"Code Injection", "Arbitrary Code Execution"},
		DataSources:    []string{"application logs", "source code analyzer", "behavior monitoring"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// ExploitAttemptRule detects general exploitation activity
func ExploitAttemptRule() DetectionRule {
	return DetectionRule{
		ID:             "EXP-001",
		Name:           "Exploitation Attempt General",
		Description:    "General detection for exploitation attempts across multiple vectors",
		DetectionLogic: `multiple failed login attempts with elevated privileges requested`,
		SyntaxType:     "siem_custom",
		Severity:       Critical,
		RuleCategory:   CategoryExploitation,
		MITREATTK:      "T1190",
		ThreatTypes:    []string{"Exploitation", "Authentication Bypass"},
		DataSources:    []string{"authentication logs", "SIEM correlation", "IDS alerts"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// MemoryCorruptionRule detects memory corruption issues
func MemoryCorruptionRule() DetectionRule {
	return DetectionRule{
		ID:             "MEM-001",
		Name:           "Memory Corruption Detected",
		Description:    "Identifies memory corruption patterns including use-after-free and double-free",
		DetectionLogic: `use_after_free or double_free detected by sanitizer`,
		SyntaxType:     "asan_report",
		Severity:       High,
		RuleCategory:   CategoryBufferOverflow,
		MITREATTK:      "T1190",
		ThreatTypes:    []string{"Use-After-Free", "Double-Free", "Memory Safety"},
		DataSources:    []string{"address sanitizer", "thread sanitizer", "valgrind"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// PrivilegeEscalationRule detects privilege escalation attempts
func PrivilegeEscalationRule() DetectionRule {
	return DetectionRule{
		ID:             "PE-001",
		Name:           "Privilege Escalation Attempt",
		Description:    "Detects unauthorized attempts to elevate system privileges",
		DetectionLogic: `non-root user executing setuid binary or sudo without authorization`,
		SyntaxType:     "auditd",
		Severity:       Critical,
		RuleCategory:   CategoryPrivilegeEscape,
		MITREATTK:      "T1068",
		ThreatTypes:    []string{"Privilege Escalation", "Unauthorized Access"},
		DataSources:    []string{"sudo logs", "audit trail", "privilege management system"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// LocalPrivilegeEscalation detects local privilege escalation
func LocalPrivilegeEscalation() DetectionRule {
	return DetectionRule{
		ID:             "LPE-001",
		Name:           "Local Privilege Escalation",
		Description:    "Identifies local privilege escalation techniques",
		DetectionLogic: `kernel exploit signature or SUID abuse detected`,
		SyntaxType:     "edr",
		Severity:       Critical,
		RuleCategory:   CategoryPrivilegeEscape,
		MITREATTK:      "T1068",
		ThreatTypes:    []string{"LPE", "Kernel Exploitation"},
		DataSources:    []string{"endpoint detection", "kernel logs", "process monitoring"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// TAMPERingDetectionRule detects tampering attempts
func TAMPERingDetectionRule() DetectionRule {
	return DetectionRule{
		ID:             "TMP-001",
		Name:           "System File Tampering",
		Description:    "Detects modification of critical system files indicating tampering",
		DetectionLogic: `/etc/passwd, /etc/shadow, or system binaries modified outside maintenance window`,
		SyntaxType:     "fim",
		Severity:       Critical,
		RuleCategory:   CategoryDefenseEvasion,
		MITREATTK:      "T1099",
		ThreatTypes:    []string{"File Tampering", "Rootkit Installation"},
		DataSources:    []string{"file integrity monitoring", "SIEM", "host-based IDS"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// AuditBypassRule detects audit bypass attempts
func AuditBypassRule() DetectionRule {
	return DetectionRule{
		ID:             "AB-001",
		Name:           "Audit Logging Bypass",
		Description:    "Identifies attempts to disable or modify audit logging",
		DetectionLogic: `auditctl stop, rmmod audit, chmod of audit logs`,
		SyntaxType:     "syslog",
		Severity:       High,
		RuleCategory:   CategoryDefenseEvasion,
		MITREATTK:      "T1070",
		ThreatTypes:    []string{"Log Manipulation", "Defense Evasion"},
		DataSources:    []string{"audit logs", "security logs", "system events"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// CredentialDumpingRule detects credential dumping
func CredentialDumpingRule() DetectionRule {
	return DetectionRule{
		ID:             "CD-001",
		Name:           "Credential Dumping Attempt",
		Description:    "Detects memory scraping or password database access indicative of credential harvesting",
		DetectionLogic: `lsass.exe process dump or /etc/passwd /etc/shadow access by unauthorized process`,
		SyntaxType:     "edr",
		Severity:       Critical,
		RuleCategory:   CategoryCredentialAccess,
		MITREATTK:      "T1003",
		ThreatTypes:    []string{"Credential Dumping", "Password Theft"},
		DataSources:    []string{"endpoint telemetry", "process monitoring", "access logs"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// PassTheHashRule detects pass-the-hash attacks
func PassTheHashRule() DetectionRule {
	return DetectionRule{
		ID:             "PTH-001",
		Name:           "Pass-the-Hash Attack",
		Description:    "Identifies pass-the-hash authentication attempts using captured NTLM hashes",
		DetectionLogic: `successful authentication from unusual source without corresponding password verification`,
		SyntaxType:     "kerberos_log",
		Severity:       Critical,
		RuleCategory:   CategoryCredentialAccess,
		MITRETechnique: "T1550",
		ThreatTypes:    []string{"Pass-the-Hash", "Authentication Bypass"},
		DataSources:    []string{"Kerberos logs", "AD logs", "auth servers"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// SuspiciousProcessRule detects suspicious processes
func SuspiciousProcessRule() DetectionRule {
	return DetectionRule{
		ID:             "PROC-001",
		Name:           "Suspicious Process Behavior",
		Description:    "Identifies processes exhibiting suspicious behavior patterns",
		DetectionLogic: `new process created from temp directory or unexpected parent process`,
		SyntaxType:     "edr",
		Severity:       Medium,
		RuleCategory:   CategoryPersistence,
		MITRETechnique: "T1053",
		ThreatTypes:    []string{"Malware Execution", "Persistence Mechanism"},
		DataSources:    []string{"endpoint detection", "process auditing", "command line logs"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// SystemModificationRule detects system modifications
func SystemModificationRule() DetectionRule {
	return DetectionRule{
		ID:             "SYS-001",
		Name:           "Critical System Modification",
		Description:    "Detects modifications to bootloaders or kernel modules",
		DetectionLogic: `modification of bootloader config or loading unsigned kernel module`,
		SyntaxType:     "bios_uefi",
		Severity:       Critical,
		RuleCategory:   CategoryPersistence,
		MITRETechnique: "T1098",
		ThreatTypes:    []string{"Bootkit", "Rootkit"},
		DataSources:    []string{"UEFI logs", "secure boot events", "kernel module loader"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// C2CommunicationRule detects command and control communication
func C2CommunicationRule() DetectionRule {
	return DetectionRule{
		ID:             "C2-001",
		Name:           "Command & Control Communication",
		Description:    "Identifies outbound connections to known malicious infrastructure",
		DetectionLogic: `connection to IP/domain flagged as C2 by threat intelligence feeds`,
		SyntaxType:     "network_siem",
		Severity:       Critical,
		RuleCategory:   CategoryCommandControl,
		MITRETechnique: "T1071",
		ThreatTypes:    []string{"C2 Channel", "Botnet Communication"},
		DataSources:    []string{"network flows", "DNS logs", "proxy logs", "threat intel feeds"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// LateralMovementRule detects lateral movement
func LateralMovementRule() DetectionRule {
	return DetectionRule{
		ID:             "LM-001",
		Name:           "Lateral Movement Attempt",
		Description:    "Detects internal network traversal and host hopping",
		DetectionLogic: `RDP/SMB connection to multiple internal hosts in short timeframe`,
		SyntaxType:     "network_traffic",
		Severity:       High,
		RuleCategory:   CategoryLateralMovement,
		MITRETechnique: "T1021",
		ThreatTypes:    []string{"Lateral Movement", "Internal Reconnaissance"},
		DataSources:    []string{"network logs", "firewall logs", "SMB/RDP audit logs"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// DataExfilRule detects data exfiltration
func DataExfilRule() DetectionRule {
	return DetectionRule{
		ID:             "DF-001",
		Name:           "Data Exfiltration",
		Description:    "Identifies data leaving organization network in suspicious ways",
		DetectionLogic: `large data transfer to external destination outside normal user behavior`,
		SyntaxType:     "dlp_siem",
		Severity:       Critical,
		RuleCategory:   CategoryExfiltration,
		MITRETechnique: "T1041",
		ThreatTypes:    []string{"Data Exfiltration", "Data Theft"},
		DataSources:    []string{"DLP logs", "network monitoring", "endpoint telemetry"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// LargeOutboundTransfer detects large outbound data transfers
func LargeOutboundTransfer() DetectionRule {
	return DetectionRule{
		ID:             "OUT-001",
		Name:           "Large Outbound Data Transfer",
		Description:    "Monitors unusually large data transfers to external destinations",
		DetectionLogic: `outbound transfer exceeds 1GB threshold or 2x normal user baseline`,
		SyntaxType:     "network_baseline",
		Severity:       Medium,
		RuleCategory:   CategoryExfiltration,
		MITRETechnique: "T1041",
		ThreatTypes:    []string{"Bulk Data Exfiltration", "Staged Exfiltration"},
		DataSources:    []string{"bandwidth monitoring", "proxy logs", "egress filtering"},
		CreatedDate:    time.Now().Format("2006-01-02"),
		LastModified:   time.Now().Format("2006-01-02"),
		Version:        "1.0",
		Status:         StatusActive,
	}
}

// Deep cloning helpers
func copyAlertEvents(src []*AlertEvent) []*AlertEvent {
	dst := make([]*AlertEvent, len(src))
	copy(dst, src)
	return dst
}
