// Package apiclientgen Go client generator. Emits a complete, idiomatic Go
// HTTP client from a normalized Model. Output is passed through go/format so it
// is guaranteed to be syntactically valid Go (a real "compiles-cleanly" check).
package apiclientgen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// GoGenerator emits a Go client package.
type GoGenerator struct{}

// Language implements Generator.
func (GoGenerator) Language() string { return "go" }

// Generate implements Generator, producing a single client.go file.
func (g GoGenerator) Generate(m *Model, packageName string) ([]GeneratedFile, error) {
	if packageName == "" {
		packageName = "apiclient"
	}
	raw := renderGo(m, packageName)
	src, err := format.Source([]byte(raw))
	if err != nil {
		return nil, fmt.Errorf("apiclientgen: generated Go failed to format (invalid syntax): %w", err)
	}
	return []GeneratedFile{{Path: "client.go", Content: string(src)}}, nil
}

func renderGo(m *Model, pkg string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by CloudAI Fusion Module 40 (apiclientgen) for %q v%s. DO NOT EDIT.\n", m.Title, m.Version)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import (\n\t\"bytes\"\n\t\"context\"\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"io\"\n\t\"net/http\"\n\t\"net/url\"\n\t\"strings\"\n)\n\n")

	emitGoTypes(&b, m.Types)
	emitGoClient(&b, m)
	emitGoMethods(&b, m)
	return b.String()
}

func emitGoTypes(b *strings.Builder, types []TypeDef) {
	for _, t := range types {
		name := pascalCase(t.Name)
		if t.Description != "" {
			fmt.Fprintf(b, "// %s %s\n", name, oneLine(t.Description))
		}
		switch {
		case t.IsEnum():
			fmt.Fprintf(b, "type %s string\n\nconst (\n", name)
			for _, e := range t.Enum {
				fmt.Fprintf(b, "\t%s%s %s = %q\n", name, pascalCase(e), name, e)
			}
			b.WriteString(")\n\n")
		case len(t.Fields) > 0:
			fmt.Fprintf(b, "type %s struct {\n", name)
			for _, f := range t.Fields {
				omit := ",omitempty"
				if f.Required {
					omit = ""
				}
				if f.Description != "" {
					fmt.Fprintf(b, "\t// %s %s\n", pascalCase(f.Name), oneLine(f.Description))
				}
				fmt.Fprintf(b, "\t%s %s `json:%q`\n", pascalCase(f.Name), goType(f.Type), f.Name+omit)
			}
			b.WriteString("}\n\n")
		case t.Alias != nil:
			fmt.Fprintf(b, "type %s %s\n\n", name, goType(t.Alias))
		default:
			fmt.Fprintf(b, "type %s map[string]any\n\n", name)
		}
	}
}

func goType(t *TypeRef) string {
	if t == nil {
		return "any"
	}
	switch t.Kind {
	case KindPrimitive:
		switch t.Primitive {
		case "string":
			return "string"
		case "integer":
			if t.Format == "int32" {
				return "int32"
			}
			return "int64"
		case "number":
			if t.Format == "float" {
				return "float32"
			}
			return "float64"
		case "boolean":
			return "bool"
		}
		return "any"
	case KindArray:
		return "[]" + goType(t.Elem)
	case KindMap:
		return "map[string]" + goType(t.Elem)
	case KindRef:
		return pascalCase(t.RefName)
	default:
		return "any"
	}
}

// returnGoType returns the Go return type and its zero-value expression for a
// success response body.
func returnGoType(t *TypeRef) (typ, zero string) {
	if t == nil {
		return "", ""
	}
	switch t.Kind {
	case KindRef:
		return "*" + pascalCase(t.RefName), "nil"
	case KindArray, KindMap:
		return goType(t), "nil"
	case KindPrimitive:
		gt := goType(t)
		switch gt {
		case "string":
			return gt, `""`
		case "bool":
			return gt, "false"
		default:
			return gt, "0"
		}
	default:
		return "json.RawMessage", "nil"
	}
}

func emitGoClient(b *strings.Builder, m *Model) {
	b.WriteString(`// Client is a generated HTTP client. Construct it with New.
type Client struct {
	baseURL    string
	httpClient *http.Client
	apiKey     string
	userAgent  string
}

// Option customizes a Client.
type Option func(*Client)

// WithHTTPClient overrides the underlying *http.Client.
func WithHTTPClient(hc *http.Client) Option { return func(c *Client) { c.httpClient = hc } }

// WithAPIKey sets a Bearer token sent in the Authorization header.
func WithAPIKey(key string) Option { return func(c *Client) { c.apiKey = key } }

// New constructs a Client for the given base URL.
func New(baseURL string, opts ...Option) (*Client, error) {
	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}
	c := &Client{
		baseURL:    strings.TrimSuffix(u.String(), "/"),
		httpClient: http.DefaultClient,
		userAgent:  "cloudai-fusion-m40/1.0",
	}
	for _, o := range opts {
		o(c)
	}
	return c, nil
}

func (c *Client) newRequest(ctx context.Context, method, path string, body any) (*http.Request, error) {
	var r io.Reader
	if body != nil {
		buf, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		r = bytes.NewReader(buf)
	}
	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, r)
	if err != nil {
		return nil, err
	}
	if c.apiKey != "" {
		req.Header.Set("Authorization", "Bearer "+c.apiKey)
	}
	req.Header.Set("User-Agent", c.userAgent)
	if r != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	req.Header.Set("Accept", "application/json")
	return req, nil
}

// APIError is returned for non-2xx responses.
type APIError struct {
	StatusCode int
	Body       string
}

func (e *APIError) Error() string {
	return fmt.Sprintf("api error: status %d: %s", e.StatusCode, e.Body)
}

func (c *Client) do(req *http.Request, out any) error {
	resp, err := c.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		b, _ := io.ReadAll(resp.Body)
		return &APIError{StatusCode: resp.StatusCode, Body: string(b)}
	}
	if out == nil {
		_, _ = io.Copy(io.Discard, resp.Body)
		return nil
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

`)
}

func emitGoMethods(b *strings.Builder, m *Model) {
	for _, op := range m.Operations {
		method := pascalCase(op.ID)

		// Assemble parameter list.
		args := []string{"ctx context.Context"}
		for _, p := range op.PathParams {
			args = append(args, camelCase(p.Name)+" "+goType(p.Type))
		}
		for _, p := range op.QueryParams {
			args = append(args, camelCase(p.Name)+" "+goType(p.Type))
		}
		if op.RequestBody != nil {
			args = append(args, "body "+goType(op.RequestBody))
		}

		retType, retZero := returnGoType(op.Success)

		// Doc comment.
		doc := op.Summary
		if doc == "" {
			doc = op.Method + " " + op.Path
		}
		fmt.Fprintf(b, "// %s %s\n", method, oneLine(doc))

		if retType == "" {
			fmt.Fprintf(b, "func (c *Client) %s(%s) error {\n", method, strings.Join(args, ", "))
		} else {
			fmt.Fprintf(b, "func (c *Client) %s(%s) (%s, error) {\n", method, strings.Join(args, ", "), retType)
		}

		// Build path with fmt.Sprintf if it has path params.
		emitGoPath(b, op)

		// Query string.
		if len(op.QueryParams) > 0 {
			b.WriteString("\tq := url.Values{}\n")
			for _, p := range op.QueryParams {
				fmt.Fprintf(b, "\tq.Set(%q, fmt.Sprintf(\"%%v\", %s))\n", p.Name, camelCase(p.Name))
			}
			b.WriteString("\tif enc := q.Encode(); enc != \"\" {\n\t\tpath += \"?\" + enc\n\t}\n")
		}

		bodyArg := "nil"
		if op.RequestBody != nil {
			bodyArg = "body"
		}
		fmt.Fprintf(b, "\treq, err := c.newRequest(ctx, %q, path, %s)\n", op.Method, bodyArg)

		if retType == "" {
			b.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
			b.WriteString("\treturn c.do(req, nil)\n}\n\n")
			continue
		}

		fmt.Fprintf(b, "\tif err != nil {\n\t\treturn %s, err\n\t}\n", retZero)
		if op.Success.Kind == KindRef {
			base := pascalCase(op.Success.RefName)
			fmt.Fprintf(b, "\tout := new(%s)\n", base)
			b.WriteString("\tif err := c.do(req, out); err != nil {\n\t\treturn nil, err\n\t}\n")
			b.WriteString("\treturn out, nil\n}\n\n")
		} else {
			fmt.Fprintf(b, "\tvar out %s\n", retType)
			fmt.Fprintf(b, "\tif err := c.do(req, &out); err != nil {\n\t\treturn %s, err\n\t}\n", retZero)
			b.WriteString("\treturn out, nil\n}\n\n")
		}
	}
}

// emitGoPath emits the `path := ...` statement, substituting {param} segments.
func emitGoPath(b *strings.Builder, op OpDef) {
	if len(op.PathParams) == 0 || !strings.Contains(op.Path, "{") {
		fmt.Fprintf(b, "\tpath := %q\n", op.Path)
		return
	}
	// Replace each {x} with %v and collect the corresponding argument in order.
	format := op.Path
	var argOrder []string
	// Find placeholders in path order.
	byName := make(map[string]ParamDef, len(op.PathParams))
	for _, p := range op.PathParams {
		byName[p.Name] = p
	}
	segments := strings.Split(op.Path, "/")
	format = ""
	for i, seg := range segments {
		if i > 0 {
			format += "/"
		}
		if strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			name := strings.Trim(seg, "{}")
			format += "%v"
			argOrder = append(argOrder, camelCase(name))
		} else {
			format += seg
		}
	}
	fmt.Fprintf(b, "\tpath := fmt.Sprintf(%q, %s)\n", format, strings.Join(argOrder, ", "))
}

// oneLine collapses a possibly multi-line description into a single line.
func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\r", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.TrimSpace(strings.Join(strings.Fields(s), " "))
}

// sortedRefNames returns the referenced type names in a model, sorted.
func sortedRefNames(m *Model) []string {
	set := map[string]bool{}
	for _, t := range m.Types {
		set[pascalCase(t.Name)] = true
	}
	out := make([]string, 0, len(set))
	for n := range set {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}
