// Package apiclientgen generators: TypeScript output.
package apiclientgen

import (
	"fmt"
	"strings"
)

// TypeScriptGenerator emits a TypeScript client module (interfaces + a fetch
// based client class).
type TypeScriptGenerator struct{}

// Language implements Generator.
func (TypeScriptGenerator) Language() string { return "typescript" }

// Generate implements Generator, producing a single index.ts file.
func (TypeScriptGenerator) Generate(m *Model, packageName string) ([]GeneratedFile, error) {
	raw := renderTS(m)
	return []GeneratedFile{{Path: "index.ts", Content: raw}}, nil
}

func renderTS(m *Model) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by CloudAI Fusion Module 40 (apiclientgen) for %q v%s\n\n", m.Title, m.Version)

	// Types.
	for _, t := range m.Types {
		name := pascalCase(t.Name)
		switch {
		case t.IsEnum():
			if t.Description != "" {
				fmt.Fprintf(&b, "/** %s */\n", oneLine(t.Description))
			}
			fmt.Fprintf(&b, "export enum %s {\n", name)
			for _, e := range t.Enum {
				fmt.Fprintf(&b, "  %s = %q,\n", pascalCase(e), e)
			}
			b.WriteString("}\n\n")
		case len(t.Fields) > 0:
			if t.Description != "" {
				fmt.Fprintf(&b, "/** %s */\n", oneLine(t.Description))
			}
			fmt.Fprintf(&b, "export interface %s {\n", name)
			for _, f := range t.Fields {
				opt := "?"
				if f.Required {
					opt = ""
				}
				fmt.Fprintf(&b, "  %s%s: %s;\n", camelCase(f.Name), opt, tsType(f.Type))
			}
			b.WriteString("}\n\n")
		case t.Alias != nil:
			fmt.Fprintf(&b, "export type %s = %s;\n\n", name, tsType(t.Alias))
		default:
			fmt.Fprintf(&b, "export type %s = Record<string, unknown>;\n\n", name)
		}
	}

	// Client class.
	b.WriteString(`export interface ClientOptions {
  apiKey?: string;
  fetch?: typeof fetch;
}

export class ApiError extends Error {
  constructor(public status: number, public body: string) {
    super("api error: status " + status + ": " + body);
  }
}

export class Client {
  private baseURL: string;
  private apiKey?: string;
  private fetchImpl: typeof fetch;

  constructor(baseURL: string, options: ClientOptions = {}) {
    this.baseURL = baseURL.replace(/\/$/, "");
    this.apiKey = options.apiKey;
    this.fetchImpl = options.fetch ?? fetch;
  }

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const headers: Record<string, string> = { Accept: "application/json" };
    if (this.apiKey) headers["Authorization"] = "Bearer " + this.apiKey;
    if (body !== undefined) headers["Content-Type"] = "application/json";
    const resp = await this.fetchImpl(this.baseURL + path, {
      method,
      headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!resp.ok) {
      throw new ApiError(resp.status, await resp.text());
    }
    if (resp.status === 204) return undefined as T;
    return (await resp.json()) as T;
  }

`)

	for _, op := range m.Operations {
		emitTSMethod(&b, op)
	}

	b.WriteString("}\n")
	return b.String()
}

func emitTSMethod(b *strings.Builder, op OpDef) {
	args := []string{}
	for _, p := range op.PathParams {
		args = append(args, camelCase(p.Name)+": "+tsType(p.Type))
	}
	for _, p := range op.QueryParams {
		opt := "?"
		if p.Required {
			opt = ""
		}
		args = append(args, camelCase(p.Name)+opt+": "+tsType(p.Type))
	}
	if op.RequestBody != nil {
		args = append(args, "body: "+tsType(op.RequestBody))
	}

	ret := "void"
	if op.Success != nil {
		ret = tsType(op.Success)
	}

	if op.Summary != "" {
		fmt.Fprintf(b, "  /** %s */\n", oneLine(op.Summary))
	}
	fmt.Fprintf(b, "  async %s(%s): Promise<%s> {\n", camelCase(op.ID), strings.Join(args, ", "), ret)

	// Path.
	if strings.Contains(op.Path, "{") {
		tmpl := op.Path
		for _, p := range op.PathParams {
			tmpl = strings.ReplaceAll(tmpl, "{"+p.Name+"}", "${"+camelCase(p.Name)+"}")
		}
		fmt.Fprintf(b, "    let path = `%s`;\n", tmpl)
	} else {
		fmt.Fprintf(b, "    let path = %q;\n", op.Path)
	}

	if len(op.QueryParams) > 0 {
		b.WriteString("    const q = new URLSearchParams();\n")
		for _, p := range op.QueryParams {
			cn := camelCase(p.Name)
			fmt.Fprintf(b, "    if (%s !== undefined) q.set(%q, String(%s));\n", cn, p.Name, cn)
		}
		b.WriteString("    const qs = q.toString();\n")
		b.WriteString("    if (qs) path += \"?\" + qs;\n")
	}

	bodyArg := "undefined"
	if op.RequestBody != nil {
		bodyArg = "body"
	}
	fmt.Fprintf(b, "    return this.request<%s>(%q, path, %s);\n", ret, op.Method, bodyArg)
	b.WriteString("  }\n\n")
}

func tsType(t *TypeRef) string {
	if t == nil {
		return "unknown"
	}
	switch t.Kind {
	case KindPrimitive:
		switch t.Primitive {
		case "string":
			return "string"
		case "integer", "number":
			return "number"
		case "boolean":
			return "boolean"
		}
		return "unknown"
	case KindArray:
		return tsType(t.Elem) + "[]"
	case KindMap:
		return "Record<string, " + tsType(t.Elem) + ">"
	case KindRef:
		return pascalCase(t.RefName)
	default:
		return "unknown"
	}
}
