// Package apiclientgen generators: Python output (dataclasses + a sync httpx
// based client class).
package apiclientgen

import (
	"fmt"
	"strings"
)

// PythonGenerator emits a Python client module: dataclasses for schemas plus a
// synchronous client class built on the httpx library.
type PythonGenerator struct{}

// Language implements Generator.
func (PythonGenerator) Language() string { return "python" }

// Generate implements Generator, producing a single client.py file.
func (PythonGenerator) Generate(m *Model, packageName string) ([]GeneratedFile, error) {
	raw := renderPython(m)
	return []GeneratedFile{{Path: "client.py", Content: raw}}, nil
}

func renderPython(m *Model) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by CloudAI Fusion Module 40 (apiclientgen) for %q v%s\n", m.Title, m.Version)
	b.WriteString("# DO NOT EDIT.\n\n")
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("from dataclasses import dataclass\n")
	b.WriteString("from enum import Enum\n")
	b.WriteString("from typing import Any, Dict, List, Optional\n\n")
	b.WriteString("import httpx\n\n\n")

	// Types: enums and dataclasses.
	for _, t := range m.Types {
		name := pascalCase(t.Name)
		switch {
		case t.IsEnum():
			if t.Description != "" {
				fmt.Fprintf(&b, "class %s(str, Enum):\n    \"\"\"%s\"\"\"\n", name, oneLine(t.Description))
			} else {
				fmt.Fprintf(&b, "class %s(str, Enum):\n", name)
			}
			if len(t.Enum) == 0 {
				b.WriteString("    pass\n")
			}
			for _, e := range t.Enum {
				fmt.Fprintf(&b, "    %s = %q\n", strings.ToUpper(snakeCase(e)), e)
			}
			b.WriteString("\n\n")
		case len(t.Fields) > 0:
			b.WriteString("@dataclass\n")
			if t.Description != "" {
				fmt.Fprintf(&b, "class %s:\n    \"\"\"%s\"\"\"\n", name, oneLine(t.Description))
			} else {
				fmt.Fprintf(&b, "class %s:\n", name)
			}
			// Required fields first, then optional (with defaults), matching
			// Python's rule that defaulted fields must follow non-defaulted ones.
			for _, f := range t.Fields {
				if f.Required {
					fmt.Fprintf(&b, "    %s: %s\n", snakeCase(f.Name), pyType(f.Type))
				}
			}
			for _, f := range t.Fields {
				if !f.Required {
					fmt.Fprintf(&b, "    %s: Optional[%s] = None\n", snakeCase(f.Name), pyType(f.Type))
				}
			}
			b.WriteString("\n\n")
		case t.Alias != nil:
			fmt.Fprintf(&b, "%s = %s\n\n\n", name, pyType(t.Alias))
		default:
			fmt.Fprintf(&b, "%s = Dict[str, Any]\n\n\n", name)
		}
	}

	// Error type and client class.
	b.WriteString(`class APIError(Exception):
    """Raised for non-2xx responses."""

    def __init__(self, status_code: int, body: str) -> None:
        self.status_code = status_code
        self.body = body
        super().__init__(f"api error: status {status_code}: {body}")


class Client:
    """Generated synchronous HTTP client."""

    def __init__(
        self,
        base_url: str,
        api_key: Optional[str] = None,
        http_client: Optional[httpx.Client] = None,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self._http = http_client or httpx.Client()

    def _request(
        self,
        method: str,
        path: str,
        params: Optional[Dict[str, Any]] = None,
        body: Any = None,
    ) -> Any:
        headers: Dict[str, str] = {"Accept": "application/json"}
        if self.api_key:
            headers["Authorization"] = "Bearer " + self.api_key
        if body is not None:
            headers["Content-Type"] = "application/json"
        resp = self._http.request(
            method,
            self.base_url + path,
            params=params,
            json=body,
            headers=headers,
        )
        if resp.status_code < 200 or resp.status_code >= 300:
            raise APIError(resp.status_code, resp.text)
        if resp.status_code == 204 or not resp.content:
            return None
        return resp.json()

`)

	for _, op := range m.Operations {
		emitPyMethod(&b, op)
	}

	return b.String()
}

func emitPyMethod(b *strings.Builder, op OpDef) {
	// Assemble the parameter list. Required path params come first, then query
	// params and body carry defaults so they can be optional.
	args := []string{"self"}
	for _, p := range op.PathParams {
		args = append(args, snakeCase(p.Name)+": "+pyType(p.Type))
	}
	for _, p := range op.QueryParams {
		args = append(args, snakeCase(p.Name)+": Optional["+pyType(p.Type)+"] = None")
	}
	if op.RequestBody != nil {
		args = append(args, "body: Any = None")
	}

	ret := "Any"
	if op.Success == nil {
		ret = "None"
	}

	fmt.Fprintf(b, "    def %s(%s) -> %s:\n", snakeCase(op.ID), strings.Join(args, ", "), ret)

	doc := op.Summary
	if doc == "" {
		doc = op.Method + " " + op.Path
	}
	fmt.Fprintf(b, "        \"\"\"%s\"\"\"\n", oneLine(doc))

	// Path construction.
	if strings.Contains(op.Path, "{") {
		tmpl := op.Path
		for _, p := range op.PathParams {
			tmpl = strings.ReplaceAll(tmpl, "{"+p.Name+"}", "{"+snakeCase(p.Name)+"}")
		}
		fmt.Fprintf(b, "        path = f%q\n", tmpl)
	} else {
		fmt.Fprintf(b, "        path = %q\n", op.Path)
	}

	// Query params.
	paramsArg := "None"
	if len(op.QueryParams) > 0 {
		b.WriteString("        params: Dict[str, Any] = {}\n")
		for _, p := range op.QueryParams {
			sn := snakeCase(p.Name)
			fmt.Fprintf(b, "        if %s is not None:\n", sn)
			fmt.Fprintf(b, "            params[%q] = %s\n", p.Name, sn)
		}
		paramsArg = "params"
	}

	bodyArg := "None"
	if op.RequestBody != nil {
		bodyArg = "body"
	}

	fmt.Fprintf(b, "        return self._request(%q, path, params=%s, body=%s)\n\n", op.Method, paramsArg, bodyArg)
}

func pyType(t *TypeRef) string {
	if t == nil {
		return "Any"
	}
	switch t.Kind {
	case KindPrimitive:
		switch t.Primitive {
		case "string":
			return "str"
		case "integer":
			return "int"
		case "number":
			return "float"
		case "boolean":
			return "bool"
		}
		return "Any"
	case KindArray:
		return "List[" + pyType(t.Elem) + "]"
	case KindMap:
		return "Dict[str, " + pyType(t.Elem) + "]"
	case KindRef:
		return pascalCase(t.RefName)
	default:
		return "Any"
	}
}
