package api_generator

import (
    "fmt"
    "os"
    "path/filepath"
    
    "gopkg.in/yaml.v3"
)

// Config holds generator configuration
type Config struct {
    OutputDir     string `yaml:"output_dir"`
    PackageName   string `yaml:"package_name"`
    IncludeAuth   bool   `yaml:"include_auth"`
    RetryPolicy   string `yaml:"retry_policy"`
}

// Generator implements OpenAPI to Go client code generation
type Generator struct {
    config    Config
    spec      *OpenAPISpec
}

// NewGenerator creates a new API client generator
func NewGenerator(config Config) *Generator {
    return &Generator{
        config: config,
    }
}

// Generate generates Go client code from OpenAPI spec
func (g *Generator) Generate(specPath string) error {
    // Parse OpenAPI spec
    specData, err := os.ReadFile(specPath)
    if err != nil {
        return fmt.Errorf("failed to read spec: %w", err)
    }
    
    var spec OpenAPISpec
    if err := yaml.Unmarshal(specData, &spec); err != nil {
        return fmt.Errorf("failed to parse spec: %w", err)
    }
    
    g.spec = &spec
    
    // Create output directory
    if err := os.MkdirAll(g.config.OutputDir, 0755); err != nil {
        return fmt.Errorf("failed to create output dir: %w", err)
    }
    
    // Generate client package
    clientCode := g.generateClientPackage()
    if err := os.WriteFile(filepath.Join(g.config.OutputDir, "client.go"), []byte(clientCode), 0644); err != nil {
        return fmt.Errorf("failed to write client.go: %w", err)
    }
    
    // Generate models
    modelsCode := g.generateModels()
    if err := os.WriteFile(filepath.Join(g.config.OutputDir, "models.go"), []byte(modelsCode), 0644); err != nil {
        return fmt.Errorf("failed to write models.go: %w", err)
    }
    
    return nil
}

// generateClientPackage generates the main client package
func (g *Generator) generateClientPackage() string {
    code := `// Code generated by CloudAI Fusion API Client Generator
// DO NOT EDIT.

package {{.PackageName}}

import (
    "bytes"
    "context"
    "encoding/json"
    "io"
    "net/http"
    "time"
)

{{range $ops := .Operations}}
{{$firstOp := index $ops 0}}
// {{$firstOp.Summary | titleCase}}
type {{$firstOp.OperationID}}Client struct {
    baseURL    string
    httpClient *http.Client
    authHeader string
}

// New{{$firstOp.OperationID}}Client creates a new client instance
func New{{$firstOp.OperationID}}Client(baseURL string, timeout time.Duration) *{{$firstOp.OperationID}}Client {
    return &{{$firstOp.OperationID}}Client{
        baseURL: baseURL,
        httpClient: &http.Client{Timeout: timeout},
    }
}

{{range $op := $ops}}
// {{toTitleCase $op.Summary}} executes the {{toTitleCase $op.OperationID}} operation
func (c *{{$firstOp.OperationID}}Client) {{toTitleCase $op.OperationID}}(ctx context.Context, req *{{$op.RequestType}}) (*{{$op.ResponseType}}, error) {
    // Serialize request body
    bodyBytes, err := json.Marshal(req)
    if err != nil {
        return nil, fmt.Errorf("failed to marshal request: %w", err)
    }
    
    // Create HTTP request
    url := c.baseURL + "/{{$op.Path}}"
    httpReq, err := http.NewRequest("{{$op.Method}}", url, bytes.NewReader(bodyBytes))
    if err != nil {
        return nil, fmt.Errorf("failed to create request: %w", err)
    }
    
    // Set headers
    httpReq.Header.Set("Content-Type", "application/json")
    if c.authHeader != "" {
        httpReq.Header.Set("Authorization", c.authHeader)
    }
    
    // Execute request with retry logic
    var resp *http.Response
    maxRetries := 3
    for attempt := 0; attempt < maxRetries; attempt++ {
        resp, err = c.httpClient.Do(httpReq)
        if err == nil {
            break
        }
        if attempt < maxRetries - 1 {
            time.Sleep(time.Duration(1<<attempt) * time.Second) // Exponential backoff
        }
    }
    if err != nil {
        return nil, fmt.Errorf("request failed after %d retries: %w", maxRetries, err)
    }
    defer resp.Body.Close()
    
    // Check status code
    if resp.StatusCode != http.StatusOK {
        body, _ := io.ReadAll(resp.Body)
        return nil, fmt.Errorf("unexpected status: %d - %s", resp.StatusCode, string(body))
    }
    
    // Deserialize response
    var result {{$op.ResponseType}}
    if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
        return nil, fmt.Errorf("failed to decode response: %w", err)
    }
    
    return &result, nil
}

{{end}}
{{end}}
`
    
    return code
}

// generateModels generates Go models from OpenAPI schema definitions
func (g *Generator) generateModels() string {
    code := `// Generated models from OpenAPI spec
package {{.PackageName}}

import (
    "encoding/json"
)

{{range $path, $paths := .Spec.Paths}}
{{range $method, $op := $paths}}
// {{$op.Summary}} represents the request/response types for this operation
type {{$op.OperationID}}Request struct {
{{range $param := $op.Parameters}}
    {{toCamelCase $param.Name}} {{getType $param.Schema.Type}} ` + "`json:\"{{toSnakeCase $param.Name}}\"`" + `
{{end}}
}

type {{$op.OperationID}}Response struct {
    Status string ` + "`json:\"status\"`" + `
    Data   interface{} ` + "`json:\"data\"`" + `
}
{{end}}
{{end}}

// MarshalJSON custom marshaller for better control over JSON output
func (r *{{$op.OperationID}}Request) MarshalJSON() ([]byte, error) {
    type Alias {{$op.OperationID}}Request
    return json.Marshal(&struct {
        *Alias
    }{
        Alias: (*Alias)(r),
    })
}
`
    
    return code
}
