apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudai-fusion-ai
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
