#!/usr/bin/env python3
"""
T2 Head-to-Head Benchmark: Streaming Mahalanobis vs sklearn Baseline

This script implements a fair comparison between:
1. CloudAI Fusion's streaming O(d²) Mahalanobis detector (Go)
2. sklearn IsolationForest (batch, tree-based)
3. sklearn LOF (batch, distance-based)

Benchmarks measure:
- Latency per vector (microseconds)
- Throughput (vectors/sec)
- Detection F1 on labeled adversarial set
- AUC-ROC

Usage:
    python sklearn_bench.py --scenario <name> --dim <d> --rho <r> --seed <s> \
        --stream-data <csv> --n-anomalies <count> --count <reps>
    
Output: JSON with latency stats, F1, AUC for both methods
"""

import json
import sys
import time
import argparse
from pathlib import Path

import numpy as np
import pandas as pd

# Try importing sklearn; provide clear error if missing
try:
    from sklearn.ensemble import IsolationForest
    from sklearn.neighbors import LocalOutlierFactor
    from sklearn.metrics import f1_score, roc_auc_score
    HAS_SKLEARN = True
except ImportError:
    HAS_SKLEARN = False
    print("ERROR: sklearn not installed. Install with: pip install scikit-learn", file=sys.stderr)


def load_streaming_data(csv_path: str) -> tuple[np.ndarray, np.ndarray]:
    """Load CSV generated by Go benchmark: scenario,dim,rho,seed,X labels"""
    df = pd.read_csv(csv_path)
    # Parse X from string representation "[x1,x2,...]"
    X_raw = df['X'].iloc[0] if 'X' in df.columns else None
    
    # For our use case, we assume the caller generates X separately
    # This function is just a placeholder - actual data passed via args
    raise NotImplementedError("Use generate_dataset() instead")


def generate_gaussian(n: int, d: int, seed: int) -> np.ndarray:
    """Generate standard normal vectors."""
    rng = np.random.default_rng(seed)
    return rng.normal(0, 1, size=(n, d))


def inject_anomalities(X: np.ndarray, ratio: float, seed: int) -> tuple[np.ndarray, np.ndarray]:
    """Inject anomalies into dataset and return labels."""
    rng = np.random.default_rng(seed + 100)
    n = len(X)
    n_anom = max(1, int(n * ratio))
    
    # Create anomalies: heavy-tailed or shifted
    X_with_anom = X.copy()
    labels = np.zeros(n, dtype=int)
    
    anom_indices = rng.choice(n, size=n_anom, replace=False)
    for idx in anom_indices:
        # Heavy-tailed anomaly: t-distribution-like
        anomaly_vec = rng.standard_t(2, size=X.shape[1]) * 3.0
        X_with_anom[idx] = anomaly_vec
        labels[idx] = 1
    
    return X_with_anom, labels


def bench_isolation_forest(X: np.ndarray, labels: np.ndarray, seed: int, n_reps: int = 5) -> dict:
    """Benchmark sklearn IsolationForest."""
    if not HAS_SKLEARN:
        return {"error": "sklearn not available"}
    
    n, d = X.shape
    scores_list = []
    latencies = []
    
    for i in range(n_reps):
        start_time = time.perf_counter_ns()
        
        # Fit IF on clean data (first portion)
        train_size = max(100, n // 2)
        clf = IsolationForest(
            n_estimators=100,
            contamination='auto',
            random_state=seed + i,
            n_jobs=-1
        )
        clf.fit(X[:train_size])
        
        # Score all points
        raw_scores = clf.decision_function(X)
        # Convert to anomaly score (higher = more anomalous)
        scores = -raw_scores
        
        end_time = time.perf_counter_ns()
        latency_us = (end_time - start_time) / 1_000
        
        scores_list.append(scores)
        latencies.append(latency_us)
    
    # Metrics on full test set
    avg_scores = np.mean(scores_list, axis=0)
    
    # Binary predictions at auto threshold
    preds = clf.predict(X)
    preds_bin = (preds == -1).astype(int)  # -1 means anomaly
    
    result = {
        "method": "isolation_forest",
        "avg_latency_us": np.mean(latencies),
        "latency_std_us": np.std(latencies),
        "throughput_vec_sec": n / (np.mean(latencies) / 1_000_000),
        "f1": f1_score(labels, preds_bin),
        "auc": roc_auc_score(labels, avg_scores) if labels.sum() > 0 and (1-labels).sum() > 0 else 0.0,
        "dimension": d,
        "samples": n
    }
    
    return result


def bench_lof(X: np.ndarray, labels: np.ndarray, seed: int, n_reps: int = 5) -> dict:
    """Benchmark sklearn LocalOutlierFactor."""
    if not HAS_SKLEARN:
        return {"error": "sklearn not available"}
    
    n, d = X.shape
    scores_list = []
    latencies = []
    
    for i in range(n_reps):
        start_time = time.perf_counter_ns()
        
        # Fit LOF on clean data (first portion)
        train_size = max(100, n // 2)
        clf = LocalOutlierFactor(
            n_neighbors=20,
            contamination='auto',
            novelty=False,
            n_jobs=-1
        )
       clf.fit_predict(X[:train_size])
        
        # Predict on full dataset
        raw_scores = clf.fit_predict(X)
        # Convert to anomaly score (lower = more anomalous)
        scores = -raw_scores
        
        end_time = time.perf_counter_ns()
        latency_us = (end_time - start_time) / 1_000
        
        scores_list.append(scores)
        latencies.append(latency_us)
    
    # Metrics
    avg_scores = np.mean(scores_list, axis=0)
    
    preds = clf.predict(X)
    preds_bin = (preds == -1).astype(int)
    
    result = {
        "method": "lof",
        "avg_latency_us": np.mean(latencies),
        "latency_std_us": np.std(latencies),
        "throughput_vec_sec": n / (np.mean(latencies) / 1_000_000),
        "f1": f1_score(labels, preds_bin),
        "auc": roc_auc_score(labels, avg_scores) if labels.sum() > 0 and (1-labels).sum() > 0 else 0.0,
        "dimension": d,
        "samples": n
    }
    
    return result


def main():
    parser = argparse.ArgumentParser(description="T2 Head-to-Head: Streaming vs sklearn Baseline")
    parser.add_argument("--scenario", type=str, default="elliptical", help="Scenario name")
    parser.add_argument("--dim", type=int, default=10, help="Feature dimension d")
    parser.add_argument("--rho", type=float, default=0.75, help="Correlation factor")
    parser.add_argument("--seed", type=int, default=0, help="Random seed")
    parser.add_argument("--n-samples", type=int, default=3000, help="Total samples N")
    parser.add_argument("--warmup", type=int, default=800, help="Warmup samples")
    testing_parser.add_argument("--n-anomalies", type=float, default=0.10, help="Anomaly ratio")
    parser.add_argument("--count", type=int, default=6, help="Number of repetitions for median")
    parser.add_argument("--output", type=str, required=True, help="Output JSON file path")
    
    args = parser.parse_args()
    
    # Generate dataset
    np.random.seed(args.seed)
    
    # Clean baseline + anomalies
    X_clean = generate_gaussian(args.n_samples, args.dim, args.seed)
    X_with_anom, labels = inject_anomalities(X_clean, args.n_anomalies, args.seed)
    
    results = {
        "benchmark": "t2_head_to_head",
        "scenario": args.scenario,
        "dimension": args.dim,
        "rho": args.rho,
        "seed": args.seed,
        "samples": args.n_samples,
        "warmup": args.warmup,
        "repetitions": args.count,
        "anomaly_ratio": args.n_anomalies,
        "competitors": {}
    }
    
    # Run sklearn benchmarks
    if HAS_SKLEARN:
        results["competitors"]["isolation_forest"] = bench_isolation_forest(
            X_with_anom, labels, args.seed, args.count
        )
        results["competitors"]["lof"] = bench_lof(
            X_with_anom, labels, args.seed, args.count
        )
    else:
        results["competitors"] = {"error": "sklearn not installed"}
    
    # Write output
    with open(args.output, 'w') as f:
        json.dump(results, f, indent=2)
    
    print(f"Benchmark results written to {args.output}")
    print(json.dumps(results, indent=2))


if __name__ == "__main__":
    main()
