// Package main - scaffold files written by `cafctl init`.
//
// `init` used to create only the evidence-chain infrastructure (keys + genesis
// chain), which left a first-time user with nothing to run. This file adds the
// two artifacts that make the project actually startable with zero dependencies:
//
//	caf-local.yaml  the local run manifest — which process to start, on which
//	                port, which endpoints it exposes, and which backends are
//	                simulated. A plain process manifest (not docker-compose) is
//	                deliberate: Docker is an optional dependency here, and the
//	                repo already ships docker-compose.yml for the full stack.
//	QUICKSTART.md   copy-pasteable commands with the expected output.
//
// The content builders are pure functions returning bytes so they can be unit
// tested without touching the filesystem.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

// quickstartScaffoldOptions parameterizes the generated files.
type quickstartScaffoldOptions struct {
	Port    int    // port the local plane binds
	RunMode string // run mode chosen by the init wizard
	Force   bool   // overwrite existing scaffold files
	// Now is injected in tests to keep generated content deterministic.
	Now func() time.Time
}

// scaffoldResult records what happened to one scaffold file.
type scaffoldResult struct {
	Path   string // path relative to the project dir
	Action string // "created" | "overwritten" | "kept existing"
	Desc   string
}

// scaffoldFile is one generated artifact.
type scaffoldFile struct {
	Name  string
	Desc  string
	Mode  os.FileMode
	Bytes []byte
	// KeepExisting protects user-authored files (README.md) from being
	// clobbered even under --force.
	KeepExisting bool
}

// quickstartScaffoldFiles builds the file set without writing anything.
func quickstartScaffoldFiles(opts quickstartScaffoldOptions) []scaffoldFile {
	if opts.Port == 0 {
		opts.Port = defaultLocalPort
	}
	if opts.RunMode == "" {
		opts.RunMode = "simulation"
	}
	if opts.Now == nil {
		opts.Now = time.Now
	}
	stamp := opts.Now().UTC().Format(time.RFC3339)

	return []scaffoldFile{
		{
			Name:  "caf-local.yaml",
			Desc:  "local run manifest (zero-dependency process list)",
			Mode:  0o644,
			Bytes: localRunManifest(opts, stamp),
		},
		{
			Name:  "QUICKSTART.md",
			Desc:  "copy-paste quickstart with expected output",
			Mode:  0o644,
			Bytes: quickstartReadme(opts, stamp),
		},
	}
}

// localRunManifest renders caf-local.yaml: the honest description of what runs
// locally, what it needs (nothing), and what is degraded.
func localRunManifest(opts quickstartScaffoldOptions, stamp string) []byte {
	base := fmt.Sprintf("http://127.0.0.1:%d", opts.Port)
	return []byte(`# CloudAI Fusion — local run manifest
# Generated by 'cafctl init' on ` + stamp + `
#
# This is a plain process manifest, not docker-compose: the local path must run
# with no daemons installed. Docker is only needed for the optional full stack
# (see optional_upgrades below).
version: 1
mode: local
run_mode: ` + opts.RunMode + `
credentials_required: none

processes:
  - name: local-plane
    kind: embedded            # runs inside the cafctl process, no container
    command: cafctl up --local --port ` + itoa(opts.Port) + `
    requires: []              # no kubernetes, no gpu, no database, no broker
    smoke_command: cafctl up --local --port ` + itoa(opts.Port) + ` --smoke
    endpoints:
      health:       ` + base + `/healthz
      ready:        ` + base + `/readyz
      version:      ` + base + `/version
      capabilities: ` + base + `/api/v1/capabilities
      providers:    ` + base + `/api/v1/cloud/providers
      instances:    ` + base + `/api/v1/cloud/instances
      evidence:     ` + base + `/api/v1/evidence/chain

backends:
  compute:
    driver: localmock         # pkg/cloudprovider.LocalMockProvider
    real: true                # genuine in-memory CRUD, deterministic IDs
    credentials: none
  evidence:
    driver: memory + ed25519  # signed hash chain; export to .caf/evidence.chain
    real: true
    anchor: simulated         # no Rekor transparency log without network config
  cluster:
    driver: none
    real: false               # needs $KUBECONFIG and the apiserver binary
  gpu:
    driver: none
    real: false               # needs NVIDIA drivers on a GPU host

# Honest degradation: the endpoints above are the complete local surface. The
# full control plane (cmd/apiserver) needs a real database, messaging and cluster
# backend and will fail fast in production run mode if any of them is simulated.
optional_upgrades:
  - name: full stack (all subsystems, containers)
    command: make docker-up-fast
    requires: [docker]
  - name: kubernetes deployment
    command: helm install cloudai-fusion deploy/helm/cloudai-fusion
    requires: [kubectl, helm, cluster]

verification:
  - cafctl doctor            # environment self-check with actionable fixes
  - cafctl status            # real-vs-simulated panel
  - cafctl verify            # offline evidence chain integrity
`)
}

// quickstartReadme renders QUICKSTART.md for the generated project.
func quickstartReadme(opts quickstartScaffoldOptions, stamp string) []byte {
	base := fmt.Sprintf("http://127.0.0.1:%d", opts.Port)
	port := itoa(opts.Port)
	return []byte(`# CloudAI Fusion — Quickstart

Generated by ` + "`cafctl init`" + ` on ` + stamp + `.
Run mode: **` + opts.RunMode + `**. Credentials required: **none**.

## 1. Check the machine (optional, ~1s)

` + "```" + `
cafctl doctor
` + "```" + `

Every ` + "`[WARN]`" + ` line names the capability you lose and the exact command that
fixes it. No optional tool (Docker, kubectl, GPU) is needed for step 2.

## 2. Start it (zero dependencies)

` + "```" + `
cafctl up --local --port ` + port + `
` + "```" + `

` + "`up`" + ` binds ` + base + `, then probes ` + "`/healthz`" + ` and ` + "`/readyz`" + `
itself — a green run means the service really answered. Ctrl+C stops it.

For a scripted/CI run that starts, verifies and exits:

` + "```" + `
cafctl up --local --port ` + port + ` --smoke
` + "```" + `

## 3. Talk to it

` + "```" + `
curl ` + base + `/healthz
curl ` + base + `/readyz
curl ` + base + `/api/v1/capabilities
curl -X POST ` + base + `/api/v1/cloud/instances -d "{\"name\":\"demo\",\"type\":\"t3.micro\"}"
curl ` + base + `/api/v1/cloud/instances
` + "```" + `

Instance CRUD is served by ` + "`pkg/cloudprovider`" + `'s LocalMockProvider: real
in-memory create/list/delete with deterministic IDs, no cloud account involved.
Each create is recorded into a signed evidence chain.

## 4. Inspect and verify

` + "```" + `
cafctl status     # real vs simulated subsystems
cafctl verify     # offline integrity check of .caf/evidence.chain
` + "```" + `

## What is real and what is not

| Subsystem | Local mode | To make it real |
|---|---|---|
| compute provider | **real** (in-memory CRUD, no credentials) | configure a cloud provider in ` + "`.caf/config.yaml`" + ` |
| evidence chain | **real** Ed25519-signed hash chain | keep it; anchor to Rekor for public transparency |
| evidence anchor | simulated | set a Rekor URL in config |
| cluster | simulated | set ` + "`$KUBECONFIG`" + ` and run ` + "`cmd/apiserver`" + ` |
| GPU | simulated | run on an NVIDIA host with drivers |

The local plane never claims a simulated backend is real: ask
` + "`" + base + `/api/v1/capabilities` + "`" + ` at any time.

## Files generated by ` + "`cafctl init`" + `

| File | Purpose |
|---|---|
| ` + "`caf-local.yaml`" + ` | local run manifest: process, port, endpoints, backend truthfulness |
| ` + "`QUICKSTART.md`" + ` | this file |
| ` + "`.caf/config.yaml`" + ` | project config (run mode, evidence, signing paths) |
| ` + "`.caf/keys/private.pem`" + ` | Ed25519 signing key (0600) |
| ` + "`.caf/public.pem`" + ` | public key — share for third-party verification |
| ` + "`.caf/evidence.chain`" + ` | exported genesis chain, verifiable offline |
`)
}

// writeQuickstartScaffold writes the scaffold into dir and returns what it did
// for each file. Existing files are preserved unless Force is set (and
// KeepExisting files are never overwritten), so re-running init is safe.
func writeQuickstartScaffold(dir string, opts quickstartScaffoldOptions) ([]scaffoldResult, error) {
	files := quickstartScaffoldFiles(opts)
	results := make([]scaffoldResult, 0, len(files))

	for _, f := range files {
		path := filepath.Clean(filepath.Join(dir, f.Name))
		_, statErr := os.Stat(path)
		exists := statErr == nil

		if exists && (f.KeepExisting || !opts.Force) {
			results = append(results, scaffoldResult{Path: f.Name, Action: "kept existing", Desc: f.Desc})
			continue
		}
		if err := os.WriteFile(path, f.Bytes, f.Mode); err != nil {
			return results, fmt.Errorf("write %s: %w", f.Name, err)
		}
		action := "created"
		if exists {
			action = "overwritten"
		}
		results = append(results, scaffoldResult{Path: f.Name, Action: action, Desc: f.Desc})
	}
	return results, nil
}
